### PR TITLE
feat(data-classes): support for code pipeline job event

### PR DESCRIPTION
**Pull request by michaelbrewer**
**Issue #, if available:**

https://github.com/awslabs/aws-lambda-powertools-python/issues/414

## Description of changes:

Add support for CodePipeline Job event data class

Code example based on the docs: 
- [Sample Python function that uses an AWS CloudFormation template](https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-invoke-lambda-function.html#actions-invoke-lambda-function-samples)

```python3
from aws_lambda_powertools import Logger
from aws_lambda_powertools.utilities.data_classes import CodePipelineJobEvent
logger = Logger()
def lambda_handler(event, context):
    """The Lambda function handler
    If a continuing job then checks the CloudFormation stack status
    and updates the job accordingly.
    If a new job then kick of an update or creation of the target
    CloudFormation stack.
    """
    event: CodePipelineJobEvent = CodePipelineJobEvent(event)
    # Extract the Job ID
    job_id = event.get_id
    # Extract the params
    params: dict = event.decoded_user_parameters
    stack = params["stack"]
    artifact_name = params["artifact"]
    template_file = params["file"]
    try:
        if event.data.continuation_token:
            # If we're continuing then the create/update has already been triggered
            # we just need to check if it has finished.
            check_stack_update_status(job_id, stack)
        else:
            # down from S3 using the credentials
            template = event.get_artifact(artifact_name, template_file)
            # Kick off a stack update or create
            start_update_or_create(job_id, stack, template)
    except Exception as e:
        # If any other exceptions which we didn't expect are raised
        # then fail the job and log the exception message.
        logger.exception("Function failed due to exception.")
        put_job_failure(job_id, "Function exception: " + str(e))
    logger.debug("Function complete.")
    return "Complete."
```

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] Update tests
* [x] Update docs
* [x] Helper functions
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by heitorlessa** [comment]
Lemme know when it's ready. I think you mentioned about adding an UTF decode before finalizing the implementation

**Comment by michaelbrewer** [comment]
@heitorlessa  i added some docs for this. So i think it is ready :)

**Comment by michaelbrewer** [comment]
@jplock  if you want to have a look too

**Review by jplock — APPROVED** [review]

**Comment by michaelbrewer** [comment]
@heitorlessa  anything missing here?

**Comment by heitorlessa** [comment]
Hey! I’ll look it over tomorrow ;-)

I’d like to make a minor release tomorrow to get this out to everyone -
it’d be nice to have some UX examples in the PR description to make it
easier to release and make this stand out

**Review by heitorlessa — APPROVED** [review]
Thanks a lot for working on this! 

> Note to self - Find a better name for this utility in 2.0, something like `event source`

**Pull request merged**
