### PR TITLE
feat: Add alb lambda event support to Parser utility

### PR DESCRIPTION
**Pull request by risenberg-cyberark**
feat: Add alb lambda event support to Parser utility #228

### CODE REVIEW

**Review by heitorlessa — CHANGES_REQUESTED** [review]
Looks great!! Two questions:

1. Could you update the docs too?
2. Do we need an envelope for the `body` field?

Here's the line where we tell customers what models Parser offers: https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/docs/content/utilities/parser.mdx#extending-built-in-models

**Comment by risenberg-cyberark** [comment]
> Looks great!! Two questions:
> 
> 1. Could you update the docs too?
> 2. Do we need an envelope for the `body` field?
> 
> Here's the line where we tell customers what models Parser offers: https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/docs/content/utilities/parser.mdx#extending-built-in-models

I didnt add the body parsing because i suppose in most cases you might want to use also the other params in the model so using an envelope would not be helpful.

**Comment by heitorlessa** [comment]
thanks a lot as always @risenberg-cyberark - As discussed, I'll commit these suggestions, and will try pushing the docs to your branch then merge. Failing that, I'll merge as-is, then send another PR with docs and suggestions implemented ;)

ETA: This Friday EOD

**Review by heitorlessa — APPROVED** [review]
Doc added - Merging

**Pull request merged**
