### PR TITLE
fix(event_handler): correct URL for OpenAPI spec in Swagger UI

### PR DESCRIPTION
**Pull request by tlinhart**
**Issue number:** #4915

### Changes

This PR corrects the URL via which the OpenAPI spec in JSON can be downloaded from Swagger UI.

### User experience

Before the fix, the URL was always `/swagger?format=json` regardless of potential custom domain name mapping.

After the change, if I created a custom domain name `custom.example.com` and mapped my API at the `/api` base path, thus accessing the Swagger UI via `https://custom.example.com/api/swagger`, I would get a correct URL for the JSON spec download `/api/swagger?format=json`.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [X] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [X] I have performed a self-review of this change
* [X] Changes have been tested
* [ ] Changes are documented
* [X] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by sthulb** [comment]
@tlinhart Thanks for the pull request! 

I have one question: You deleted two test cases, I'm curious about why? Did it break your new implementation somehow?

**Comment by tlinhart** [comment]
> I have one question: You deleted two test cases, I'm curious about why? Did it break your new implementation somehow?

I tried to explain it in the [linked issue](https://github.com/aws-powertools/powertools-lambda-python/issues/4915#issuecomment-2284006939). Yeah, the fix has broken the tests as they relied on the `path` being passed into the `generate_swagger_html`. More importantly, they became superfluous after the fix.

**Review by sthulb — APPROVED** [review]
I've confirmed everything still works as expected. Thanks for the PR @tlinhart !

**Comment by sthulb** [comment]
Unrelated to this PR, but `_get_base_path(self)` has an issue too, it'll return the stage variable even if using a custom domain, which might be annoying to some users.

**Comment by tlinhart** [comment]
> Unrelated to this PR, but `_get_base_path(self)` has an issue too, it'll return the stage variable even if using a custom domain, which might be annoying to some users.


Yeah, check out my message on Discord about it - https://discord.com/channels/1006478942305263677/1006527338621710376/1272632575818727476. The method works correctly but covers only the case when one accesses the API via generated API endpoint URL. To cover the custom domain names it would have to be enhanced as I tried to propose.

**Pull request merged**
