### PR TITLE
docs(idempotency): fix description in `Advanced` table

### LINKED ISSUE #5193: Docs: Improve parameter descriptions in Idempotency `Advanced` table
### What were you searching in the docs?

What each parameter does exactly for the Idempotency utility.

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/utilities/idempotency/#advanced

### How can we improve?

Complete the sentence with the missing information.

### Got a suggestion in mind?

_No response_

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

### PR DESCRIPTION
**Pull request by garysassano**
**Issue number:** #5193 

### Changes

- Improved the description for `payload_validation_jmespath` to make it more clear

Issue: #5193 

Related TS Issue: aws-powertools/powertools-lambda-typescript#3098
Related TS PR: aws-powertools/powertools-lambda-typescript#3092

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [ ] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [ ] I have performed a self-review of this change
* [ ] Changes have been tested
* [ ] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by leandrodamascena** [comment]
Hi @garysassano! Thank you very much for submitting this PR! We made some changes to our branches because we had to release V3 and this PR became impossible to merge due to too many conflicts.

Do you mind closing this PR and opening another one against develop? You may need to pull the repository/branches again because we changed a lot.

**Comment by garysassano** [comment]
@leandrodamascena I updated my branch.

**Comment by leandrodamascena** [comment]
Thanks a lot @garysassano! I'm approving this PR and will wait for @dreamorosi to merge it into TS before merging it here. Since you're working there, I'll wait to see if there are any other changes.

**Review by leandrodamascena — APPROVED** [review]
APPROVED!

**Comment by dreamorosi** [comment]
I just merged the the corresponding PR on the TS repo, feel free to merge this whenever you want.

**Pull request merged**
