### PR TITLE
refactor(tracer): make capture_lambda_handler type more generic

### LINKED ISSUE #4795: Using `event_source` decorator with `tracer.capture_lambda_handler` decorator
### Static type checker used

pyright/pylance

### AWS Lambda function runtime

3.12

### Powertools for AWS Lambda (Python) version

latest

### Static type checker info

```
Argument of type "(event: SNSEvent, context: Unknown) -> dict[str, Unknown]" cannot be assigned to parameter "lambda_handler" of type "((Dict[Unknown, Unknown], Any) -> Any) | ((Dict[Unknown, Unknown], Any, Dict[Unknown, Unknown] | None) -> Any) | None" in function "capture_lambda_handler"
  Type "(event: SNSEvent, context: Unknown) -> dict[str, Unknown]" is incompatible with type "((Dict[Unknown, Unknown], Any) -> Any) | ((Dict[Unknown, Unknown], Any, Dict[Unknown, Unknown] | None) -> Any) | None"
    Type "(event: SNSEvent, context: Unknown) -> dict[str, Unknown]" is incompatible with type "(Dict[Unknown, Unknown], Any) -> Any"
      Parameter 1: type "Dict[Unknown, Unknown]" is incompatible with type "SNSEvent"
        "Dict[Unknown, Unknown]" is incompatible with "SNSEvent"
    Type "(event: SNSEvent, context: Unknown) -> dict[str, Unknown]" is incompatible with type "(Dict[Unknown, Unknown], Any, Dict[Unknown, Unknown] | None) -> Any"
      Function accepts too many positional parameters; expected 2 but received 3
        Parameter 1: type "Dict[Unknown, Unknown]" is incompatible with type "SNSEvent"
          "Dict[Unknown, Unknown]" is incompatible with "SNSEvent"
```

### Code snippet

```python
from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.utilities.data_classes import SNSEvent, event_source

tracer = Tracer()
logger = Logger()


@logger.inject_lambda_context
@tracer.capture_lambda_handler
@event_source(data_class=SNSEvent)
def lambda_handler(event: SNSEvent, context: LambdaContext): ...
```

### Possible Solution

When using the `tracer.capture_lambda_handler` decorator with `event_source` decorator Pylance is complaining about type mismatch. Checking the `logger.inject_lambda_context` I think we could use `AnyCallableT` .

Does that make sense to create a PR for this? Or is too broad of a type? I will create a small PR anyway.

### PR DESCRIPTION
**Pull request by aminalaee**
**Issue number:** #4795 

## Summary

When using the tracer.capture_lambda_handler decorator with event_source decorator Pylance is complaining about type mismatch.

### Changes

> Please provide a summary of what's being changed

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [ ] I have performed a self-review of this change
* [ ] Changes have been tested
* [ ] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by leandrodamascena** [comment]
Hello @aminalaee! Thanks for sending this PR!
I see you are now using `AnyCallableT` in `capture_lambda_handler`, the same type we use in the other methods. I just want to understand if you have had problems with this or if this is just an improvement you are making? Either way, we appreciate your help.

I will wait to hear from the customer before opening the issue to link to this PR. I'm adding a label `do-not-merge`.

**Comment by leandrodamascena** [comment]
> Hello @aminalaee! Thanks for sending this PR! I see you are now using `AnyCallableT` in `capture_lambda_handler`, the same type we use in the other methods. I just want to understand if you have had problems with this or if this is just an improvement you are making? Either way, we appreciate your help.
> 
> I will wait to hear from the customer before opening the issue to link to this PR. I'm adding a label `do-not-merge`.

Opz, sorry! I saw the issue right now!

**Comment by heitorlessa** [comment]
AnyCallableT is to signal we expect a function with any signature, returning anything - Callable[..., Any]

In this context, what we should be solving is turning the first argument (event) into a generic type so customers (and parser/data class) can mutate to something other than a Dict.

If you look closely at capture_method, AnyCallableT makes sense as it applies to any function. 

PS: For Logger, we need to revisit it. I don't remember if it's using AnyCallableT because we needed a quick fix OR if we needed to unblock Logger outside Lambda (prolly wrong as we use the context object too)

**Comment by leandrodamascena** [comment]
Hi @aminalaee! I'm working to merge this PR tomorrow at the latest.

**Comment by leandrodamascena** [comment]
Hi @aminalaee! I agree with @heitorlessa about making the first parameter more generic, so that we can handle mutations when the customer uses the event source or the parser, or even any external/custom decorator.

While we don't support fully static typing, we love to make progress and improve the developer experience. A Lambda function will always require two parameters, the first being the event and the second being the context, if we change the `capture_lambda_handler` signature to what you propose, we run the risk of someone accidentally removing one of the two arguments and pyright/mypy not complaining about it, which I think would make for a less than ideal experience. See this example:

image

I changed the `capture_lambda_handler` signature to make the first and second arguments mandatory, the first being a more generic type and the second being `Any`, since context is a specialized Lambda class (`awslambdaric.lambda_context.LambdaContext`) but can be our implementation `LambdaContext`. The third argument is optional and can be anything, a `kwarg`, a dependency injection, a pydantic model, anything that can help make testing simpler in a local environment.

Thanks again for bringing up this problem.

@sthulb I need your review here.

**Review by sthulb — APPROVED** [review]

**Comment by aminalaee** [comment]
@leandrodamascena thanks for the review and commits 👍

**Pull request merged**
