### PR TITLE
feat(utilities): processor for SNS events

### PR DESCRIPTION
**Pull request by Nr18**
**Issue #, if available:**

## Description of changes:

Simple `SNSProcessor` to handle incoming SNS events

**Checklist**

 

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Nr18** [comment]
I always seem to have think of an additional angle after I submit stuff, but I think it makes sense to not do an SNS specific processor but a records specific one.

This allows you to do the same for example with S3 events without the need of an additional processor.

**Comment by heitorlessa** [comment]
Hey @Nr18 could you write a RFC on this to allow for discussion first?

At a first glance, SNS only sends a single record despite its data structure allowing for more

**Comment by michaelbrewer** [comment]
> Hey @Nr18 could you write a RFC on this to allow for discussion first?
> 
> At a first glance, SNS only sends a single record despite its data structure allowing for more

Based on this kind of thing i have added convenience methods to PR: https://github.com/awslabs/aws-lambda-powertools-python/pull/159

```python3
event = SNSEvent(event)
# Return the message for the first sns event record
message = event.sns_message
```

**Comment by Nr18** [comment]
Closing this PR as #159 would cover the same functionality.

**Pull request closed without merging**
