### PR TITLE
fix(data-classes): include milliseconds in scalar types

### LINKED ISSUE #503: bug: aws scalar type for AWSDateTime should include milliseconds
**What were you trying to accomplish?**

## Expected Behavior

AWSDateTime - An extended ISO 8601 date and time string in the format YYYY-MM-DDThh:mm:ss.sssZ.

## Current Behavior

AWSDateTime is not including the millisecond part `sss`.

## Possible Solution

Generate timestamps to include the milliseconds

## Steps to Reproduce (for bugs)

```python3
> print(aws_datetime())
2021-07-02T17:09:47Z
````

## Environment

* **Powertools version used**: 1.17.0
* **Packaging format (Layers, PyPi)**: PyPi
* **AWS Lambda function runtime:** Python 3.8

### PR DESCRIPTION
**Pull request by michaelbrewer**
**Issue #, if available:**

#503

## Description of changes:

Set the formatted output to include milliseconds

fixes #503

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] Update tests
* [X] Update docs
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

## Breaking change checklist

Potentially a breaking change if expecting only seconds.

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by michaelbrewer** [comment]
@heitorlessa  I think that `%f` might cause issues with AppSync dates as they are expecting milliseconds.

**Comment by michaelbrewer** [comment]
@heitorlessa seems to work as microseconds, so should i still trim off the extra 3 positions? or leave it

**Comment by heitorlessa** [comment]
thanks for the fix!! Let's trim off to stay as milliseconds (`[:-3]`) to stay compliant whether validation catches server-side - Depending on how much data one pumps in, this should also save on costs

**Review by heitorlessa — CHANGES_REQUESTED** [review]
Trim last three to stick as ms `[:-3]`

**Review by heitorlessa — APPROVED** [review]
Thanks for the changes, Mike!

Note to self: break down `test_data_classes` as it's 1.3K LOC atm

**Comment by michaelbrewer** [comment]
> Thanks for the changes, Mike!
> 
> Note to self: break down `test_data_classes` as it's 1.3K LOC atm

It would be great if pytest can run parts in parallel :). Then i would definitely help split up things.

**Pull request merged**
