### PR TITLE
feat: Add S3 lambda event support to Parser utility #224

### PR DESCRIPTION
**Pull request by risenberg-cyberark**
**Issue #, if available:**
feat: Add S3 lambda event support to Parser utility #224

Added schema files and tests to parser utility

### CODE REVIEW

**Review by heitorlessa — CHANGES_REQUESTED** [review]
Awesome - two questions as with the other PRs:

1. Could you please update the docs on this new model?
2. Do we want to cover S3 Batch Operations too?

Docs portion: https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/docs/content/utilities/parser.mdx#extending-built-in-models

On 2, here's the example payload which seems pretty quick to create a model from: https://docs.aws.amazon.com/lambda/latest/dg/services-s3-batch.html

**Comment by risenberg-cyberark** [comment]
> Awesome - two questions as with the other PRs:
> 
> 1. Could you please update the docs on this new model?
> 2. Do we want to cover S3 Batch Operations too?
> 
> Docs portion: https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/docs/content/utilities/parser.mdx#extending-built-in-models
> 
> On 2, here's the example payload which seems pretty quick to create a model from: https://docs.aws.amazon.com/lambda/latest/dg/services-s3-batch.html

Sure, i'll try my best

**Comment by heitorlessa** [comment]
thanks a lot as always @risenberg-cyberark - As discussed, I'll commit these suggestions, and will try pushing the docs to your branch then merge. Failing that, I'll merge as-is, then send another PR with docs and suggestions implemented ;)

ETA: This Friday EOD

**Review by heitorlessa — APPROVED** [review]
Docs added - Merging

**Pull request merged**
