### PR TITLE
feat(layers): add new comercial region Israel(Tel Aviv)

### LINKED ISSUE #2902: Feature request: Add Tel Aviv region to the Lambda Layers Deployment
### Use case

AWS recently launched new region:

Israel (Tel Aviv) - il-central-1

https://aws.amazon.com/blogs/aws/now-open-aws-israel-tel-aviv-region/

This region doesn't support arm64, so we need to add in exception list.

### Solution/User Experience

Deploy Lambda Layers to these new region.

### Alternative solutions

_No response_

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### PR DESCRIPTION
**Pull request by leandrodamascena**
**Issue number:** #2902 

### Changes

Expand public Lambda Layer deployment to the Israel(Tel Aviv) region.

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [ ] I have performed a self-review of this change
* [ ] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by leandrodamascena** [comment]
Please do not merge before making sure we have enabled this new region in the layer account.

Need help here @sthulb.

**Comment by leandrodamascena** [comment]
The region is now enabled. Ready to review @heitorlessa.

**Review by heitorlessa — CHANGES_REQUESTED** [review]
was this deployed already?

image

**Comment by leandrodamascena** [comment]
> was this deployed already?
> 
> 
> 
> image
> 
> 

It doesn't. But since we release/publish layers and bump version, the documentation will be updated to the version 41, right?!

I don't know if we need to add all versions in this new region.

**Review by heitorlessa — APPROVED** [review]

**Comment by heitorlessa** [comment]
Approving on the basis that `:40` is a placeholder and we won't publish a Layer with 2.22.0 for that region alone, since it'd need a full release.

Our publish layer is locked for sealed source code created at the beginning of a release (for good measure).

**Pull request merged**
