### PR TITLE
docs(appsync): add mutation example and infrastructure fix

### LINKED ISSUE #1953: Docs: create Example for usage of AppSync for Mutations
### What were you searching in the docs?

How to us the use the Framework for Mutations.

### Is this related to an existing documentation section?

https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/docs/core/event_handler/appsync.md

### How can we improve?

add sample code for todo creation and update.

### Got a suggestion in mind?

_No response_

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

### PR DESCRIPTION
**Pull request by heitorlessa**
**Issue number:** #1953

### Changes

> Please provide a summary of what's being changed

This PR extends the getting started example by adding a mutation. Previously, we only had queries, making it harder to work with mutations for newcomers of Event Handler AppSync.

* [x] Add `createTodo` mutation in the schema
* [x] Enable mutations in the GraphQL Schema (`schema { mutation: Mutation }`)
* [x] Updated code snippet to include a mutation event resolution (`getting_started_graphql_api_resolver.py`)
* [x] Improved documentation experience when viewing multiple sample events with a new tab (`Sample events`)

It also improves the example infrastructure to ease reproducing it in the future:

* [x] Replace `Definition` with `DefinitionS3Location` within `TodosApiSchema` AppSync API resource. This removes schema duplication and prevent error-prone updates by centralizing in a single source of truth
* [x] Add cfn-lint exception since `DefinitionS3Location` only works with SAM CLI
* [x] Add `requirements.txt` with dependencies used so it can be built with `sam build --use-container`
* [x] Add `samconfig.toml` to ease deploying next time (`sam deploy`, or `sam deploy -g` in other accounts). On the fence about this one as someone else deploying will change the file; will keep it for now as it doesn't harm

### User experience

> Please share what the user experience looks like before and after this change

**Schema extended**

image

**New Sample events tab**

image

**Sample resolver extended**

image

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by tb102122** [comment]
@heitorlessa I think you like to remove "or Title under Todo" in the type explanation section or?
For completion we should also extend the event examples. 
image

I assume something like this:

```
{
    "arguments": {
        "title": "Titel of DEMO ToDo"
    },
    "identity": null,
    "source": null,
    "request": {
        "headers": {
            "x-forwarded-for": "1.2.3.4, 5.6.7.8",
            "accept-encoding": "gzip, deflate, br",
            "cloudfront-viewer-country": "NL",
            "cloudfront-is-tablet-viewer": "false",
            "referer": "https://eu-west-1.console.aws.amazon.com/appsync/home?region=eu-west-1",
            "via": "2.0 9fce949f3749407c8e6a75087e168b47.cloudfront.net (CloudFront)",
            "cloudfront-forwarded-proto": "https",
            "origin": "https://eu-west-1.console.aws.amazon.com",
            "x-api-key": "da1-c33ullkbkze3jg5hf5ddgcs4fq",
            "content-type": "application/json",
            "x-amzn-trace-id": "Root=1-606eb2f2-1babc433453a332c43fb4494",
            "x-amz-cf-id": "SJw16ZOPuMZMINx5Xcxa9pB84oMPSGCzNOfrbJLvd80sPa0waCXzYQ==",
            "content-length": "114",
            "x-amz-user-agent": "AWS-Console-AppSync/",
            "x-forwarded-proto": "https",
            "host": "ldcvmkdnd5az3lm3gnf5ixvcyy.appsync-api.eu-west-1.amazonaws.com",
            "accept-language": "en-US,en;q=0.5",
            "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0",
            "cloudfront-is-desktop-viewer": "true",
            "cloudfront-is-mobile-viewer": "false",
            "accept": "*/*",
            "x-forwarded-port": "443",
            "cloudfront-is-smarttv-viewer": "false"
        }
    },
    "prev": null,
    "info": {
        "parentTypeName": "Mutation",
        "selectionSetList": [
            "title",
            "id"
        ],
        "selectionSetGraphQL": "{\n  title\n  id\n}",
        "fieldName": "createTodo",
        "variables": {}
    },
    "stash": {}
}

**Comment by heitorlessa** [comment]
Great catch! I’ll fix these, generate an event just to be safe, and merge
it.

Thanks a lot again Tobias for helping us out

**Comment by heitorlessa** [comment]
Now it's ready @tb102122 - Added a sample [`createTodo` JSON event (real event)](https://github.com/heitorlessa/aws-lambda-powertools-python/blob/docs/event-handler-appsync-mutation/examples/event_handler_graphql/src/getting_started_create_todo.json), grouped all events under a new tab `Sample events` to ease discoverability and improve reading experience.

Also fixed unrelated issues as I was reproducing it with our sample infrastructure.

image

**Comment by heitorlessa** [comment]
I'll assume the 🎉 reaction as approval ;) Since @leandrodamascena and @rubenfonseca are unavailable this week, I'm merging and rebuilding the latest doc to prevent any confusion until our next release.

Thanks a lot @tb102122 once again.

**Pull request merged**
