### PR TITLE
fix(parser): make etag optional field on S3 notification events

### PR DESCRIPTION
**Pull request by benjamingorman**
**Issue number:** https://github.com/aws-powertools/powertools-lambda-python/issues/4156

## Summary

`etag` is not guaranteed to be present on an S3 event (if it's a `DeleteObject` event for example) so this MR changes the type of `etag` on `S3EventNotificationObjectModel` to be `Optional`.

### Changes

> Please provide a summary of what's being changed

* Modified `S3EventNotificationObjectModel`
* Modified `S3EventBridgeNotificationObject`

### User experience

> Please share what the user experience looks like before and after this change

Before: S3 DeleteObject event fails to parse, with a pydantic validation error

After: S3 DeleteObject event is parsed correctly

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

It simply reflects the reality of the event in AWS.

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by leandrodamascena** [comment]
Thanks for submitting the PR @benjamingorman! I think we need to change other fields like `size`, `version_id` and `sequencer` in the event source data class. They are already optional in Parser and based on the payload you sent they are not present.

Let me fix this and push a commit.

**Comment by am29d** [comment]
Make also sure to remove the `etag` and `size` from the test event in https://github.com/aws-powertools/powertools-lambda-python/blob/fe26d1c9e1cb6478f1b4818363f251056948b4f1/tests/events/s3EventBridgeNotificationObjectDeletedEvent.json#L20

**Comment by heitorlessa** [comment]
Looking...

**Comment by heitorlessa** [comment]
Pushed the fixes for tests and used sane defaults for `etag`  _(S3->EventBridge)_ and `eTag` _(S3->Lambda/SNS/SQS)_.

Improved docstrings to explain when that's the case. Pending CI and we can merge.

**Comment by dreamorosi** [comment]
For reference, I have tested the events with an actual stack, these are two examples of events that trigger a function:

```json
{
    "version": "0",
    "id": "1d0e793f-a560-c0b2-9f0f-f0046cf8d051",
    "detail-type": "Object Created",
    "source": "aws.s3",
    "account": "536254204126",
    "time": "2024-05-07T09:31:21Z",
    "region": "eu-west-1",
    "resources": [
        "arn:aws:s3:::s3teststack-mybucketf68f3ff0-gscrrokfnvnw"
    ],
    "detail": {
        "version": "0",
        "bucket": {
            "name": "s3teststack-mybucketf68f3ff0-gscrrokfnvnw"
        },
        "object": {
            "key": "surprised-pikachu.gif",
            "size": 2638774,
            "etag": "fb21c5a0ff18e29aab890d1d1f6d6e64",
            "sequencer": "006639F4E9AAD27BAD"
        },
        "request-id": "ACJYMRYT9T7HS3KE",
        "requester": "536254204126",
        "source-ip-address": "15.248.3.15",
        "reason": "PutObject"
    }
}
```

and 

```json
{
    "version": "0",
    "id": "46bf2718-5e27-a74d-ec6b-2d95d4e21844",
    "detail-type": "Object Deleted",
    "source": "aws.s3",
    "account": "536254204126",
    "time": "2024-05-07T09:31:52Z",
    "region": "eu-west-1",
    "resources": [
        "arn:aws:s3:::s3teststack-mybucketf68f3ff0-gscrrokfnvnw"
    ],
    "detail": {
        "version": "0",
        "bucket": {
            "name": "s3teststack-mybucketf68f3ff0-gscrrokfnvnw"
        },
        "object": {
            "key": "surprised-pikachu.gif",
            "sequencer": "006639F508B96A7690"
        },
        "request-id": "11K82SGF9X2HBEKD",
        "requester": "536254204126",
        "source-ip-address": "15.248.3.15",
        "reason": "DeleteObject",
        "deletion-type": "Permanently Deleted"
    }
}
```

**Comment by heitorlessa** [comment]
checking shortly, just updating the main issue

**Pull request merged**
