### PR TITLE
refactor(event_source): fix type hint

### LINKED ISSUE #3568: Static typing: Untyped event_source decorator with mypy --strict
### Static type checker used

mypy (project's standard)

### AWS Lambda function runtime

3.12

### Powertools for AWS Lambda (Python) version

2.30.2

### Static type checker info

Just `mypy --strict`, with mypy version 1.8.0.
Output: `error: Untyped decorator makes function "handler" untyped  [misc]`

### Code snippet

```python
$ pip freeze
aws-lambda-powertools==2.30.2
mypy==1.8.0
mypy-extensions==1.0.0
typing_extensions==4.9.0

$ cat main.py  --plain
from typing import Any
from aws_lambda_powertools.utilities.data_classes import SQSEvent, event_source
from aws_lambda_powertools.utilities.typing import LambdaContext
@event_source(data_class=SQSEvent)
def handler(event: SQSEvent, _context: LambdaContext) -> dict[str, Any]:
    return {}

$ mypy --strict main.py
main.py:7: error: Untyped decorator makes function "handler" untyped  [misc]
Found 1 error in 1 file (checked 1 source file)
```

### Possible Solution

Very similar to #1060 which is claimed to be solved, but this issue appears in the latest release, mypy in strict mode still doesnt understand the return type. Maybe it came back?

### PR DESCRIPTION
**Pull request by robmoss2k**
**Issue number:** #3568

### Changes

Add the `Any` return type to the event_source function definition. The `handler` argument already specifies that it will return `Any` and `event_source` returns whatever `handler` returns.

### User experience

`mypy --strict` won't throw `error: Untyped decorator makes function "handler" untyped  [misc]` any longer.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [X] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [X] I have performed a self-review of this change
* [X] Changes have been tested
* [X] Changes are documented
* [X] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by robmoss2k** [comment]
Fixes #3568.

**Comment by leandrodamascena** [comment]
Hello @robmoss2k! Thanks for submitting this PR and putting effort to solve this problem. 

Can you export the libs that are installed in your virtual environment and how you are running the tests? I'm still having problems here with strict check in mypy.

My tests applying this fix:

### requirements.txt
```
aws-lambda-powertools==2.36.0
aws-xray-sdk==2.12.1
boto3==1.34.10
botocore==1.34.10
fastjsonschema==2.19.1
jmespath==0.10.0
mypy==1.8.0
mypy-extensions==1.0.0
python-dateutil==2.8.2
s3transfer==0.10.0
six==1.16.0
tomli==2.0.1
typing_extensions==4.9.0
urllib3==1.26.18
wrapt==1.16.0
```

### main.py
```python
from typing import Any
from aws_lambda_powertools.utilities.data_classes import SQSEvent, event_source
from aws_lambda_powertools.utilities.typing import LambdaContext

@event_source(data_class=SQSEvent)
def handler(event: SQSEvent, _context: LambdaContext) -> dict[str, Any]:
    return {}
```

### running mypy
```sh
(.venv) ➜  leo mypy -V
mypy 1.8.0 (compiled: yes)
(.venv) ➜  leo mypy --strict main.py
main.py:5: error: Untyped decorator makes function "handler" untyped  [misc]
Found 1 error in 1 file (checked 1 source file)
```
Thanks and please let me know if I'm missing something.

**Comment by rubenfonseca** [comment]
It seems this change is breaking a lot of things on our CI

**Comment by robmoss2k** [comment]
> It seems this change is breaking a lot of things on our CI

It's not finished. I need a solid block of time to spend on it. Don't approve it before it's finished. I will get back to it. Feels like I've bitten off more than I can chew... But I don't like to lose.

**Comment by heitorlessa** [comment]
No worries, it's a hard task, as not everything can be made into strict typing -- for the decorator factory, the new `ParamSpec` type will be of great help.

**Comment by leandrodamascena** [comment]
Hello @robmoss2k! Thank you for putting in the effort here and helping us make the project more strict/strongly typed, which is a big challenge, we really appreciate your effort. But we are closing this PR as not planned for now. 

We are about to release Powertools v3 and we will not prioritize that at the moment as we will put v2 in maintenance mode soon. Another thing is that refactoring method signatures and introducing changes to such important utilities can create some unexpected side effects, which we don't want at this point.

For Powertools v4, we plan to refactor the modules and make the project more strict typed. 

Again, thanks for your time here and feel free to reopen if you want.

**Pull request closed without merging**
