### PR TITLE
fix(event_handler): custom serializer recursive values when using data validation

### LINKED ISSUE #4658: Bug: custom serializer isn't being used by nested dict
### Expected Behaviour

The custom serializer should be passed to all sub-functions

### Current Behaviour

The custom serializer is not being called, it's passed only on the first `jsonable_encoder` run.
https://github.com/aws-powertools/powertools-lambda-python/blob/develop/aws_lambda_powertools/event_handler/openapi/encoders.py#L112

### Code snippet

```python
from aws_lambda_powertools.event_handler.openapi.encoders import jsonable_encoder
from bson import Decimal128


def custom_serializer(obj):
    if isinstance(obj, Decimal128):
        return int(obj.to_decimal())

    return obj


# work
print(jsonable_encoder(Decimal128('123'), custom_serializer=custom_serializer))

# doesn't work
print(jsonable_encoder({'dec': Decimal128('123')}, custom_serializer=custom_serializer))
```

### Possible Solution

pass `custom_serializer` to all functions, as this is a recursive function as mentioned in https://github.com/aws-powertools/powertools-lambda-python/issues/3892#issuecomment-1983683318

### Steps to Reproduce

run the code snippet (:

### Powertools for AWS Lambda (Python) version

2.40.1

### AWS Lambda function runtime

3.11

### Packaging format used

PyPi

### Debugging logs

```python
Traceback (most recent call last):
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 279, in _dump_other
    data = dict(obj)
           ^^^^^^^^^
TypeError: 'Decimal128' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 283, in _dump_other
    data = vars(obj)
           ^^^^^^^^^
TypeError: vars() argument must have __dict__ attributeTraceback (most recent call last):
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 279, in _dump_other
    data = dict(obj)
           ^^^^^^^^^
TypeError: 'Decimal128' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 283, in _dump_other
    data = vars(obj)
           ^^^^^^^^^
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 147, in jsonable_encoder
    return _dump_other(
           ^^^^^^^^^^^^
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 286, in _dump_other
    raise ValueError(errors) from e
ValueError: [TypeError("'Decimal128' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "xxxxxxxxxxxxxx/c.py", line 19, in <module>
    print(jsonable_encoder({'dec': Decimal128('123')}, custom_serializer=custom_serializer))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 113, in jsonable_encoder
    return _dump_dict(
           ^^^^^^^^^^^
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 226, in _dump_dict
    encoded_value = jsonable_encoder(
                    ^^^^^^^^^^^^^^^^^
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 157, in jsonable_encoder
    raise SerializationError(
aws_lambda_powertools.event_handler.openapi.exceptions.SerializationError: ('Unable to serialize the object 123 as it is not a supported type. Error details: [TypeError("\'Decimal128\' object is not iterable"), TypeError(\'vars() argument must have __dict__ attribute\')]', 'See: https://docs.powertools.aws.dev/lambda/python/latest/core/event_handler/api_gateway/#serializing-objects')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 147, in jsonable_encoder
    return _dump_other(
           ^^^^^^^^^^^^
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 286, in _dump_other
    raise ValueError(errors) from e
ValueError: [TypeError("'Decimal128' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "xxxxxxxxxxxxxx/c.py", line 19, in <module>
    print(jsonable_encoder({'dec': Decimal128('123')}, custom_serializer=custom_serializer))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 113, in jsonable_encoder
    return _dump_dict(
           ^^^^^^^^^^^
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 226, in _dump_dict
    encoded_value = jsonable_encoder(
                    ^^^^^^^^^^^^^^^^^
  File "xxxxxxxxxxxxxx/.venv/lib/python3.11/site-packages/aws_lambda_powertools/event_handler/openapi/encoders.py", line 157, in jsonable_encoder
    raise SerializationError(
aws_lambda_powertools.event_handler.openapi.exceptions.SerializationError: ('Unable to serialize the object 123 as it is not a supported type. Error details: [TypeError("\'Decimal128\' object is not iterable"), TypeError(\'vars() argument must have __dict__ attribute\')]', 'See: https://docs.powertools.aws.dev/lambda/python/latest/core/event_handler/api_gateway/#serializing-objects')
```

### PR DESCRIPTION
**Pull request by heitorlessa**
**Issue number:** #4658

## Summary

Recursively include custom serializer for all supported data types (dicts, sequences, dataclasses, Pydantic Models).

Previously, we were only using a `custom_serializer` for top-level keys. That meant the `custom_serializer` reference was getting lost during recursion.

With this change, we can now correctly serialize custom items in a list, custom values in a dict, custom values in a dataclass/Pydantic model, etc. however deep.

### Changes

> Please provide a summary of what's being changed

### User experience

> Please share what the user experience looks like before and after this change

```python
from aws_lambda_powertools.event_handler.openapi.encoders import jsonable_encoder
from bson import Decimal128


def custom_serializer(obj):
    if isinstance(obj, Decimal128):
        return int(obj.to_decimal())

    return obj


# work
print(jsonable_encoder(Decimal128('123'), custom_serializer=custom_serializer))

# works AFTER this PR gets merged
print(jsonable_encoder({'dec': Decimal128('123')}, custom_serializer=custom_serializer))
```

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by heitorlessa** [comment]
Will check CI later this afternoon.

**Comment by heitorlessa** [comment]
@leandrodamascena when you can, I'm gonna need your help on how to best test pydantic version differences [to get this to pass](https://github.com/aws-powertools/powertools-lambda-python/pull/4664/commits/bff9b81b75a3f32c3abd9684010cd01a6367be08#diff-543da2c36ff5759f0327f5ed15670e81b8d0df96b41a29198e221602d16bfa8fR242).

I'll get back to this late afternoon / evening

**Comment by leandrodamascena** [comment]
> @leandrodamascena when you can, I'm gonna need your help on how to best test pydantic version differences [to get this to pass](https://github.com/aws-powertools/powertools-lambda-python/pull/4664/commits/bff9b81b75a3f32c3abd9684010cd01a6367be08#diff-543da2c36ff5759f0327f5ed15670e81b8d0df96b41a29198e221602d16bfa8fR242).
> 
> I'll get back to this late afternoon / evening

Hey @heitorlessa! Two things here:

1 - I found a bug in the Nox tests that is installing Pydantic 2.0 in the v1.0 test only in some situations, I don't know why, but it is. To fix this, I'll change [this line](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/noxfile.py#L151) to `@nox.parametrize(" pydantic", ["1.10,<2.0", "2.0"])`.

2 - This test is wrong because it is not possible to do this with Pydantic to dump JSON. The first thing we do when we detect that it is a Pydantic model is to dump it into JSON and then invoke the `jsonable_encoder` function again with this JSON, and in this new invocation it is possible to use `custom_serializer`. I understand what you tried to do, but we need to change this test a little.
image

I'll fix both problems tomorrow morning! Thanks for working on this.

**Review by leandrodamascena — APPROVED** [review]
Hello @heitorlessa! I removed the change where we added `custom_serializer` to the Pydantic model because it will never work. When using Pydantic, the customer must handle the serializer within the model itself, otherwise Pydantic will fail.

Reference: https://github.com/pydantic/pydantic/issues/7991

For me this PR is approved!

**Comment by heitorlessa** [comment]
Gotcha! thanks a lot @leandrodamascena and for fixing the pydantic nox unrelated bug too; I didn't know `field_serializer` existed.

```python
class MyResult(BaseModel):
    name: str
    token_list: TokenList

    @field_serializer('token_list')
    def token_list_serializer(self, token_list: TokenList, _info):
        return orjson.Fragment(orjson.dumps(token_list.model_dump()))
```

**Comment by heitorlessa** [comment]
@sthulb need your approval as Leandro pushed a fix to this PR

**Review by sthulb — APPROVED** [review]

**Pull request merged**
