### PR TITLE
docs: fix syntax errors and line highlights

### PR DESCRIPTION
**Pull request by michaelbrewer**
**Issue #, if available:**
- https://github.com/awslabs/aws-lambda-powertools-python/issues/1013

## Description of changes:

- fix line number highlights
- fix missing imports
- fix syntax error
- fix indents
- fix example code rendering

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] Update tests
* [X] Update docs
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

-----
[View rendered docs/core/event_handler/api_gateway.md](https://github.com/gyft/aws-lambda-powertools-python/blob/fix-docs/docs/core/event_handler/api_gateway.md)
[View rendered docs/tutorial/index.md](https://github.com/gyft/aws-lambda-powertools-python/blob/fix-docs/docs/tutorial/index.md)

### CODE REVIEW

**Comment by heitorlessa** [comment]
Besides tutorial, I wonder how this happened and how we can prevent this from happening again.

Need to run git blame. Not sure if it was always there, people's markdown linter (happened before), something else entirely.

Might be worth experiment with code snippets being separate Python files that can be lint - Cons is line highlights that become slightly more laborious but should pay off (--8<-)

**Comment by michaelbrewer** [comment]
> Besides tutorial, I wonder how this happened and how we can prevent this from happening again.
> 
> Need to run git blame. Not sure if it was always there, people's markdown linter (happened before), something else entirely.
> 
> Might be worth experiment with code snippets being separate Python files that can be lint - Cons is line highlights that become slightly more laborious but should pay off (--8<-)

Importing from an actual example helps (coz you can run the some linters and auto formatting. Otherwise the line high lights suck, i wish it was different ie:

```python title="My title" marker="(<)"
import json  #  (<)

# Another one to highlight (<)

```

**Comment by heitorlessa** [comment]
> Besides tutorial, I wonder how this happened and how we can prevent this from happening again.
> 
> Need to run git blame. Not sure if it was always there, people's markdown linter (happened before), something else entirely.
> 
> Might be worth experiment with code snippets being separate Python files that can be lint - Cons is line highlights that become slightly more laborious but should pay off (--8<-) 

https://squidfunk.github.io/mkdocs-material/reference/code-blocks/

We use this in parts of the doc. Need to give a try to see if line highlights still work. If it does, then change Makefile and CI to lint them -- this will
prevent from happening and have all snippets formatted consistently too

Other bits can be solved with a markdown linter.

**Comment by michaelbrewer** [comment]
@heitorlessa  adding https://github.com/awslabs/aws-lambda-powertools-python/issues/1013 in risk of this issue being closed.

**Comment by heitorlessa** [comment]
Thanks a lot again @michaelbrewer - merging it before we release it

**Pull request merged**
