### PR TITLE
docs(apigateway): add all resolvers in testing your code section for accuracy

### PR DESCRIPTION
**Pull request by bnsouza**
**Issue number:** [#1686](https://github.com/awslabs/aws-lambda-powertools-python/issues/1686)

### Changes

I've changed the example for testing API Gateway. Changed the `examples/event_handler_rest/src/assert_http_response.py` and `docs/core/event_handler/api_gateway.md`.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] I have performed a self-review of this change
* [X] Changes have been tested
* [X] Changes are documented
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

-----
[View rendered docs/core/event_handler/api_gateway.md](https://github.com/bnsouza/aws-lambda-powertools-python/blob/docs/fix-example-test-apigateway/docs/core/event_handler/api_gateway.md)

### CODE REVIEW

**Comment by heitorlessa** [comment]
@bnsouza could you review the changes I've made just in case I missed anything?

Changes:

* Split testing snippets per resolver to prevent the confusion we've had
* Ensure imports, minimal_event, and correlation path used match the specific resolver

**Review by bnsouza — COMMENTED** [review]
It's perfect! If you don't mind, can I insert as a comment the URL from AWS Docs with full examples of the events payload?

I had to search because when I tested with query parameters, I made it wrong! 🤣

**Comment by bnsouza** [comment]
I made it! But if you think it's better remove or change, it's ok!

Abraços!

**Comment by heitorlessa** [comment]
np at all! For future reference, we add all variants of the payloads we encounter under "test/events" - we found docs not to be a reliable source at times

https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/tests/events/apiGatewayProxyV2Event.json

**Review by heitorlessa — APPROVED** [review]

**Comment by heitorlessa** [comment]
Merging now - thank you again! Nice touch on adding the payload link as a comment!

**Pull request merged**
