### PR TITLE
chore(docs): correct markdown based on markdown lint

### PR DESCRIPTION
**Pull request by michaelbrewer**
**Issue #, if available:**

## Description of changes:

Changes:
- Correct the readme me link to feature flags correct location is `https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/feature_flags/`
- Fix some of the json examples in `feature_flags.md`
- run [markdownlint](https://github.com/DavidAnson/markdownlint) against all of the `*.md` files

> Unfortunately alot of white space changes, so in the diff `Hide whitespace changes` make help hide the noise

**Checklist**

 

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] Update tests
* [x] Update docs
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by michaelbrewer** [comment]
> awesome, while you're at it, could you also include this small fix here? The closing is invalid
> 
> https://github.com/awslabs/aws-lambda-powertools-python/blob/f627b02ee3fb52859a620413bb8310c74c778046/docs/utilities/feature_flags.md#L373

done. there is also general formatting issues with the json

**Comment by michaelbrewer** [comment]
@heitorlessa - I run through all of the markdown files through [vs code - markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint), see what you think

**Comment by michaelbrewer** [comment]
> 1.8K changes hahaha perhaps we split into a separate PR so we know we experimented with markdown linting?

Minimal changes here: https://github.com/awslabs/aws-lambda-powertools-python/pull/605

**Comment by michaelbrewer** [comment]
@heitorlessa i synced up the changes. So if you want to look at the impact this. I think once you have the linting working nicely. The impact will be less for future updates.

**Comment by heitorlessa** [comment]
Does it render correctly in the docs after all changes? and if you were to copy/paste the code snippets from docs, does it still work correctly e.g. indentation?

Haven't had a chance to pull this PR and try these, so I'd trust if you say so and merge it ;)

**Comment by michaelbrewer** [comment]
@heitorlessa - it does in my random testing. But I will have to think of a faster way to validate all of them.

**Review by heitorlessa — APPROVED** [review]

**Pull request merged**
