### PR TITLE
feat(parameters): Allow callable transforms

### PR DESCRIPTION
**Pull request by whardier**
**Issue #, if available:**

#893 

## Description of changes:

Add in changes to base parameter classes and feature flags appconfig store to allow for callable transforms to be used as well as the available stringy references.

**Checklist**

 

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ran-isenberg** [comment]
I'm not that having a parameter as both str and callable is the best approach. maybe have it is as string, set to custom and add another param for the callable?
also, what about error handling? what happens if the transform raises an exception?

**Comment by whardier** [comment]
I don't like it either but I am working within a compatible solution.  Ideally transform would be an instance of a transform object with a .transform method and a list of compatible key suffixes.

Error handling is the same as the json and binary methods.  all exceptions lead to None unless transform errors are set to raise.

**Comment by whardier** [comment]
perhaps the best approach is to register transform classes by string an key suffix and then do a lookup and execute them generically.

**Comment by heitorlessa** [comment]
@whardier we appreciate the bias for action in implementing a feature you need, however, we'd like to hear from more customers that this is necessary & requirements before diving into the implementation where we can iron out maintainability, etc.

Locking this PR for now until we hear from more customers

**Pull request closed without merging**
