### PR TITLE
feat(validator): include missing data elements from a validation error

### PR DESCRIPTION
**Pull request by michaelbrewer**
**Issue #, if available:**

## Description of changes:

Current implementation will just build a message from the `JsonSchemaValueException` like:

```
'Failed schema validation. Error: data must contain [\'message\', \'username\'] properties, Path: [\'data\'], Data: {\'message\': \'hello_world\'}'
```

Which is not presentable and missing some of the data elements.  This change updates `SchemaValidationError` to include more data elements from `JsonSchemaValueException`

## New fields are:

- validation_message :  Containing human-readable information what is wrong (e.g. `data.property[index] must be smaller than or equal to 42`)
- name : name of a path in the data structure (e.g. `data.property[index]`)
- path: `path` as an array in the data structure (e.g. `['data', 'property', 'index']`),
- value : The invalid value
- definition : The full rule `definition` (e.g. `42`)
- rule : - `rule` which the `data` is breaking (e.g. `maximum`)
- rule_definition : Any, optional The specific rule `definition` (e.g. `42`)

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] Update tests
* [X] Update docs
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by heitorlessa — CHANGES_REQUESTED** [review]
Two small changes: 1/ Test to ensure we don't break the previous behaviour, and 2/ Either docs or an example of how to leverage the new attributes to make it presentable

**Comment by michaelbrewer** [comment]
@heitorlessa not sure what to change

**Review by heitorlessa — APPROVED** [review]
Thanks a lot, Mike!

**Comment by heitorlessa** [comment]
> @heitorlessa not sure what to change

My internet didn't download all details and I couldn't see the tests -- this time I can, just merged, sorry for the confusion

**Pull request merged**
