### PR TITLE
fix(license): add MIT-0 license header

### PR DESCRIPTION
**Pull request by e42sh**
**Issue number:** #1881

### Changes

* Add MIT-0 header to LICENSE file for better interoperability (LICENSE analyzers). Followed https://en.wikipedia.org/wiki/MIT_License#MIT_No_Attribution_License + https://github.com/aws/mit-0

### User experience

* No impact

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary> No.

**RFC issue number**:

Checklist:

* [x] Migration process documented
* [x] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by heitorlessa** [comment]
Hey @meckhardt, thank you for the proactive addition. Could you share some background on how you bumped into this?

All of our PRs need an issue (a maintenance issue template in this case) in order to be merged. We'll check with our OSPO on the appropriate outcome for the `LICENSE` file.

**Comment by hyandell** [comment]
Hopping on the OSPO side. The title is an optional field ( https://spdx.org/licenses/MIT-0.json ), but it is embarrassing that our predating OSI-approval template didn't include the title.

I'm +1 to merge this PR. It's not necessary, as that field is optional, but I'm going to suggest we update our template to start defaulting to include the title.

**Comment by e42sh** [comment]
Thanks @heitorlessa @hyandell  that you take this change seriously. 

 I had an issue with Sonatype Nexus IQ about MIT-0 being recognized as a proprietary license which led to a rejected build for one of my customers. While searching for the root cause @fabge found a difference between the license text given on https://en.wikipedia.org/wiki/MIT_License#MIT_No_Attribution_License and  https://github.com/aws/mit-0.  Sonatype Support states that this shouldn't be an issue with their recent Nexus IQ release. However, I wanted to share this finding with you.

**Comment by e42sh** [comment]
I added  #1881

**Review by heitorlessa — APPROVED** [review]

**Pull request merged**
