### PR TITLE
fix(feature_flags): Fix for but 714 -- only evaluting first rule

### PR DESCRIPTION
**Pull request by gwlester**
**Issue #, if available:** #714

## Description of changes:

Corrected indentation in evaluate rules so that it will only return the default after all rules are evaluated.

**Checklist**

 

* [ ] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [ ] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by heitorlessa** [comment]
cc @risenberg-cyberark I believe that's the expected behaviour in the original schema, no?

from the docs:

> You can have multiple rules with different names. **The rule engine will return the first result when_match of the matching rule configuration**, or default value when none of the rules apply.

**Comment by heitorlessa** [comment]
I'd take that back - Another part of the docs also says:

> **For multiple conditions**, we will evaluate the **list of conditions as a logical AND**, so all conditions needs to match to return when_match value.

I'd defer to @risenberg-cyberark who did the original schema to confirm before proceeding here, as we'll need remove ambiguity from docs too thereafter.

**Comment by risenberg-cyberark** [comment]
I remembered i solved a similar bug in the conditions about 1.5 months ago with the same indendation in the conditions checks: _evaluate_conditions. 
Yep, it's the same silly indentation issue.
The docs seem ok to me.
Anyways, thx for the fix. It's correct.

**Comment by risenberg-cyberark** [comment]
I think the pr should also fix a test for multiple rules where the second rule matches, not the first.

**Comment by heitorlessa** [comment]
> I remembered i solved a similar bug in the conditions about 1.5 months ago with the same indendation in the conditions checks: _evaluate_conditions. Yep, it's the same silly indentation issue. The docs seem ok to me. Anyways, thx for the fix. It's correct.

I remembered that but wasn't sure if was fixed by pushing identation or pulling it. Either way, if you have the bandwidth for fixing the test and merge conflict by Monday, I can include it in Tue/Wed release as it's an important one

**Comment by gwlester** [comment]
> > I remembered i solved a similar bug in the conditions about 1.5 months ago with the same indentation in the conditions checks: _evaluate_conditions. Yep, it's the same silly indentation issue. The docs seem ok to me. Anyways, thx for the fix. It's correct.
> 
> I remembered that but wasn't sure if it was fixed by pushing indentation or pulling it. Either way, if you have the bandwidth for fixing the test and merge conflict by Monday, I can include it in Tue/Wed release as it's an important one

The code I pushed allows multi-rules to work as well as multi-conditions.  
multi-conditions are **and**.  multi-rules are **or**

Personally, I think this is critical.

**Comment by risenberg-cyberark** [comment]
> > > I remembered i solved a similar bug in the conditions about 1.5 months ago with the same indentation in the conditions checks: _evaluate_conditions. Yep, it's the same silly indentation issue. The docs seem ok to me. Anyways, thx for the fix. It's correct.
> > 
> > 
> > I remembered that but wasn't sure if it was fixed by pushing indentation or pulling it. Either way, if you have the bandwidth for fixing the test and merge conflict by Monday, I can include it in Tue/Wed release as it's an important one
> 
> The code I pushed allows multi-rules to work as well as multi-conditions. multi-conditions are **and**. multi-rules are **or**
> 
> Personally, I think this is critical.

I agree

**Comment by risenberg-cyberark** [comment]
I'm on it

**Comment by gwlester** [comment]
Ok, a dumb question -- the coverage report says this decreased the coverage by 0.04%-- but the only file touched (...owertools/utilities/feature_flags/feature_flags.py) is at 100% coverage!

What gives?

**Comment by gwlester** [comment]
> I think the pr should also fix a test for multiple rules where the second rule matches, not the first.

Unless I'm misreading it, that is what **test_flags_conditions_rule_match_multiple_actions_multiple_rules_multiple_conditions** is supposed to do with:
```python
    # match second rule
    toggle = feature_flags.evaluate(name="my_feature", context={"tenant_id": "4446", "username": "az"}, default=False)
```

I have no idea how this test was passing before.

**Comment by risenberg-cyberark** [comment]
it was working because the match value of the rule was the same as the default value of the feature.
When i change expected_value_second_check to be True and run the test. it fails, because it doesnt match on the second rule.
After your fix, the test works with expected_value_second_check = True or False, because it returns the correct value.
I'm creating a PR. 
see https://github.com/awslabs/aws-lambda-powertools-python/pull/724

**Comment by risenberg-cyberark** [comment]
@gwlester  I think you pushed the commits to the wrong branch

**Comment by gwlester** [comment]
> @gwlester I think you pushed the commits to the wrong branch
No, pulled the changes into here when attempting to resolve conflicts -- so we close this PR and just go with yours since it fixes the test as well as the code, right?

**Comment by risenberg-cyberark** [comment]
> > @gwlester I think you pushed the commits to the wrong branch
> > No, pulled the changes into here when attempting to resolve conflicts -- so we close this PR and just go with yours since it fixes the test as well as the code, right?

indeed.
I meant that you added the other new actions here.

**Pull request closed without merging**
