### PR TITLE
feat(mypy): add mypy support to makefile

### PR DESCRIPTION
**Pull request by michaelbrewer**
**Issue #, if available:**

- https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/3

## Description of changes:

- Add `mypy` as a dev dependency 
- Add `mypy` as task in the Makefile
- Put in some initial fixes (mostly just ignore untyped imports)

### Example usage

```shell
$ make mypy 
poetry run mypy aws_lambda_powertools
aws_lambda_powertools/tracing/extensions.py:11: error: Skipping analyzing "aws_xray_sdk.ext.aiohttp.client": found module but no type hints or library stubs
aws_lambda_powertools/tracing/extensions.py:11: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
aws_lambda_powertools/tracing/base.py:9: error: Argument 1 to "contextmanager" has incompatible type "Callable[[BaseProvider, Any, KwArg(Any)], ContextManager[Any]]"; expected "Callable[..., Iterator[<nothing>]]"
aws_lambda_powertools/tracing/base.py:22: error: Argument 1 to "contextmanager" has incompatible type "Callable[[BaseProvider, Any, KwArg(Any)], AsyncContextManager[Any]]"; expected "Callable[..., Iterator[<nothing>]]"
aws_lambda_powertools/utilities/parameters/base.py:96: error: Incompatible types in assignment (expression has type "Union[Dict[Any, Any], bytes, None]", variable has type "str")
aws_lambda_powertools/utilities/parameters/base.py:154: error: Incompatible types in assignment (expression has type "Dict[str, str]", variable has type "Dict[str, Union[str, bytes, Dict[Any, Any], None]]")
aws_lambda_powertools/utilities/parameters/base.py:154: note: "Dict" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
aws_lambda_powertools/utilities/parameters/base.py:154: note: Consider using "Mapping" instead, which is covariant in the value type
aws_lambda_powertools/utilities/parameters/base.py:160: error: Incompatible types in assignment (expression has type "str", variable has type "Tuple[str, Optional[str]]")
aws_lambda_powertools/utilities/parameters/base.py:161: error: Argument 1 to "get_transform_method" has incompatible type "Tuple[str, Optional[str]]"; expected "str"
aws_lambda_powertools/utilities/parameters/base.py:165: error: Invalid index type "Tuple[str, Optional[str]]" for "Dict[str, Union[str, bytes, Dict[Any, Any], None]]"; expected type "str"
aws_lambda_powertools/utilities/parameters/base.py:165: error: Argument 1 to "transform_value" has incompatible type "Union[str, bytes, Dict[Any, Any], None]"; expected "str"
aws_lambda_powertools/utilities/parameters/base.py:169: error: Incompatible return value type (got "Dict[str, Union[str, bytes, Dict[Any, Any], None]]", expected "Union[Dict[str, str], Dict[str, Dict[Any, Any]], Dict[str, bytes]]")
aws_lambda_powertools/tracing/tracer.py:19: error: "LazyLoader" has no attribute "core"
aws_lambda_powertools/tracing/tracer.py:509: error: "Callable[..., Any]" has no attribute "__wrapped__"
aws_lambda_powertools/logging/formatter.py:109: error: Cannot assign to a method
aws_lambda_powertools/logging/formatter.py:109: error: Invalid self argument "LambdaPowertoolsFormatter" to attribute function "converter" with type "Callable[[Optional[float]], struct_time]"
aws_lambda_powertools/logging/formatter.py:131: error: Invalid self argument "LambdaPowertoolsFormatter" to attribute function "converter" with type "Callable[[Optional[float]], struct_time]"
aws_lambda_powertools/logging/formatter.py:131: error: Too many arguments
aws_lambda_powertools/logging/formatter.py:184: error: Argument 1 has incompatible type "str"; expected "Dict[Any, Any]"
aws_lambda_powertools/logging/formatter.py:204: error: Item "None" of "Optional[Type[BaseException]]" has no attribute "__name__"
aws_lambda_powertools/utilities/parameters/ssm.py:87: error: Signature of "get" incompatible with supertype "BaseProvider"
aws_lambda_powertools/utilities/data_classes/sqs_event.py:78: error: Return type "Optional[SQSMessageAttribute]" of "__getitem__" incompatible with return type "SQSMessageAttribute" in supertype "dict"
aws_lambda_powertools/utilities/data_classes/sqs_event.py:78: error: Return type "Optional[SQSMessageAttribute]" of "__getitem__" incompatible with return type "SQSMessageAttribute" in supertype "Mapping"
aws_lambda_powertools/utilities/data_classes/sqs_event.py:80: error: Argument 1 to "SQSMessageAttribute" has incompatible type "SQSMessageAttribute"; expected "Dict[str, Any]"
aws_lambda_powertools/logging/logger.py:355: error: Item "None" of "Optional[PowertoolsFormatter]" has no attribute "remove_keys"
aws_lambda_powertools/utilities/idempotency/persistence/base.py:104: error: Argument 1 to "loads" has incompatible type "Optional[str]"; expected "Union[str, bytes]"
aws_lambda_powertools/utilities/idempotency/persistence/base.py:286: error: Unsupported target for indexed assignment ("Optional[LRUDict]")
aws_lambda_powertools/utilities/idempotency/persistence/base.py:291: error: Item "None" of "Optional[LRUDict]" has no attribute "get"
aws_lambda_powertools/utilities/idempotency/persistence/base.py:301: error: Unsupported right operand type for in ("Optional[LRUDict]")
aws_lambda_powertools/utilities/idempotency/persistence/base.py:302: error: Item "None" of "Optional[LRUDict]" has no attribute "__delitem__"
aws_lambda_powertools/middleware_factory/factory.py:121: error: Item "None" of "Optional[Callable[..., Any]]" has no attribute "__qualname__"
Found 29 errors in 10 files (checked 108 source files)
make: *** [mypy] Error 1

```

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] Update tests
* [X] Update docs
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by heitorlessa — CHANGES_REQUESTED** [review]
Let's create a `mypy.ini` file to best ignore untyped libraries among other features we can enable like a pydantic plugin.

* Config: https://mypy.readthedocs.io/en/stable/config_file.html

Example that we can start with, errors will become easier to read too:

```ini
[mypy]
warn_return_any=False
warn_unused_configs=True
no_implicit_optional=True
warn_redundant_casts=True
warn_unused_ignores=True
pretty = True
show_column_numbers = True
show_error_codes = True
show_error_context = True

[mypy-jmespath]
ignore_missing_imports=True

```

**Comment by michaelbrewer** [comment]
@heitorlessa `no_implicit_optional=True` seems a bit strict to me.

**Comment by michaelbrewer** [comment]
> @heitorlessa `no_implicit_optional=True` seems a bit strict to me.

Before this was an implicit optional 

```python
def foo(msg: str = None):
   ...
```

now it needs to be 

```python
from typing import Optional


def foo(msg: Optional[str] = None):
   ...
```

**Comment by heitorlessa** [comment]
> > @heitorlessa `no_implicit_optional=True` seems a bit strict to me.
> 
> Before this was an implicit optional
> 
> ```python
> def foo(msg: str = None):
>    ...
> ```
> 
> now it needs to be
> 
> ```python
> from typing import Optional
> 
> 
> def foo(msg: Optional[str] = None):
>    ...
> ```

This is correct actually. It's the issue that @Nr18 was having too. Challenge with Python is the mutable defaults

**Review by heitorlessa — APPROVED** [review]

**Pull request merged**
