### PR TITLE
feat(event_sources): support for custom properties in ActiveMQEvent

### LINKED ISSUE #2018: Feature request: Custom Properties support in ActiveMQ Event Source Data Class
### Use case

Lambda Event Source now supports JMS custom properties but [ActiveMQEvent](https://awslabs.github.io/aws-lambda-powertools-python/2.9.1/utilities/data_classes/#active-mq) doesn't expose `properties` property.

Sample event from Lambda docs now with `properties` 

```json
{
   "eventSource": "aws:mq",
   "eventSourceArn": "arn:aws:mq:us-west-2:111122223333:broker:test:b-9bcfa592-423a-4942-879d-eb284b418fc8",
   "messages": [
      { 
        "messageID": "ID:b-9bcfa592-423a-4942-879d-eb284b418fc8-1.mq.us-west-2.amazonaws.com-37557-1234520418293-4:1:1:1:1", 
        "messageType": "jms/text-message",
        "deliveryMode": 1,
        "replyTo": null,
        "type": null,
        "expiration": "60000",
        "priority": 1,
        "correlationId": "myJMSCoID",
        "redelivered": false,
        "destination": { 
          "physicalName": "testQueue" 
        },
        "data":"QUJDOkFBQUE=",
        "timestamp": 1598827811958,
        "brokerInTime": 1598827811958, 
        "brokerOutTime": 1598827811959, 
        "properties": {
          "index": "1",
          "doAlarm": "false",
          "myCustomProperty": "value"
        }
      },
      { 
        "messageID": "ID:b-9bcfa592-423a-4942-879d-eb284b418fc8-1.mq.us-west-2.amazonaws.com-37557-1234520418293-4:1:1:1:1",
        "messageType": "jms/bytes-message",
        "deliveryMode": 1,
        "replyTo": null,
        "type": null,
        "expiration": "60000",
        "priority": 2,
        "correlationId": "myJMSCoID1",
        "redelivered": false,
        "destination": { 
          "physicalName": "testQueue" 
        },
        "data":"LQaGQ82S48k=",
        "timestamp": 1598827811958,
        "brokerInTime": 1598827811958, 
        "brokerOutTime": 1598827811959, 
        "properties": {
          "index": "1",
          "doAlarm": "false",
          "myCustomProperty": "value"
        }
      }
   ]
}
```

### Solution/User Experience

Add new property named `properties` to allow access to custom properties received by a message broker.

### Alternative solutions

_No response_

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [ ] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

### PR DESCRIPTION
**Pull request by alexaiss**
### Changes

Adds custom properties to ActiveMQ event after Lambda Event Source Mappings added the support

### User experience

Users will now be able to interpret custom properties at runtime for their ActiveMQ messages delivered via Lambda Event Source Mappings.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] I have performed a self-review of this change
* [X] Changes have been tested
* [X] Changes are documented
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by rubenfonseca** [comment]
Hi @alexaiss thank you for your PR!

In order for us to handle it, you'll need to create an issue first. Please check the [CONTRIBUTING guide](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/CONTRIBUTING.md#contributing-via-pull-requests) for more details.

Can you please create an issue about this feature?

**Comment by heitorlessa** [comment]
I created an issue #2018 but I couldn't trace the origin though - **when** custom properties were added, or was it always there and we missed it?

Went down the rabbit hole reading every release note until November 2022 and couldn't find it either. However, Lambda MQ docs do have the `properties` key, [Lambda Java Events merged @alexaiss PR](https://github.com/aws/aws-lambda-java-libs/pull/408) too so they must be familiar, so going ahead with this PR.

**Comment by heitorlessa** [comment]
We don't have permissions to push to your fork, so please apply this patch so tests can pass and we can merge. We'll make a release tomorrow, hopefully this can be fixed earlier to be included.

Thank you!

---

```patch
From ee9343e814853d41b5f66057575946a221052cff Mon Sep 17 00:00:00 2001
From: heitorlessa <lessa@amazon.co.uk>
Date: Thu, 16 Mar 2023 12:47:29 +0100
Subject: [PATCH] fix(tests): add custom properties

---
 tests/events/activeMQEvent.json | 8 +++++---
 1 file changed, 5 insertions(+), 3 deletions(-)

diff --git a/tests/events/activeMQEvent.json b/tests/events/activeMQEvent.json
index 57d206ba..6bcae212 100644
--- a/tests/events/activeMQEvent.json
+++ b/tests/events/activeMQEvent.json
@@ -13,7 +13,10 @@
       },
       "timestamp": 1598827811958,
       "brokerInTime": 1598827811958,
-      "brokerOutTime": 1598827811959
+      "brokerOutTime": 1598827811959,
+      "properties": {
+        "testKey": "testValue"
+      }
     },
     {
       "messageID": "ID:b-9bcfa592-423a-4942-879d-eb284b418fc8-1.mq.us-west-2.amazonaws.com-37557-1234520418293-4:1:1:1:1",
@@ -30,7 +33,6 @@
       "properties": {
         "testKey": "testValue"
       }
-
     },
     {
       "messageID": "ID:b-9bcfa592-423a-4942-879d-eb284b418fc8-1.mq.us-west-2.amazonaws.com-37557-1234520418293-4:1:1:1:1",
@@ -49,4 +51,4 @@
       }
     }
   ]
-}
+}
\ No newline at end of file
-- 
2.37.1 (Apple Git-137.1)


```

**Comment by alexaiss** [comment]
Hi Heitor and Ruben,

Thanks for the comments. Apologies for missing creating an issue, thanks for doing that for me! And thanks for finding the bug, not sure how I missed that but it is fixed now to my knowledge.

I'm from one of the Lambda teams that maintains ActiveMQ Lambda integration, we recently added this as a minor improvement, not a feature launch. Thanks!

**Comment by rubenfonseca** [comment]
Looking at this now

**Review by rubenfonseca — APPROVED** [review]
Thank you for the background, and for submitting this fix! Looking forward to release this later today.

**Pull request merged**
