### PR TITLE
chore(ci): create PRs not push

### PR DESCRIPTION
**Pull request by heitorlessa**
**Issue number:** #2210

## No longer necessary, closing shortly

Broken down into multiple PRs to ease reviewing (in order):

* https://github.com/awslabs/aws-lambda-powertools-python/pull/2239
* https://github.com/awslabs/aws-lambda-powertools-python/pull/2239
* https://github.com/awslabs/aws-lambda-powertools-python/pull/2240

## Summary

Move to new model of creating PR for specific staged changes

### Changes

> Please provide a summary of what's being changed

- [x] Build changelog on push
- [x] Create PR for docs
- [x] Remove PR permission for jobs that don't need it
- [x] Require PR_TITLE only... use the same for commit message
- [x] Defensively bump version from each step
- [x] Create version bump PR from release
- [x] Drop redundant Changelog job
- [x] Breakdown `post_release` job to reduce permissions
  - [x] one job to bump version and create PR
  - [x] one job to notify issues, discussions, PRs that a new version is up
- [x] Create docs PR with newest Layer ARN as part of the release to keep trunk up-to-date

**Optional**

> Leave that aside, we need a tech debt issue to prevent this PR to become difficult to review.

- [x] Setup git client script and replace `Git client setup and refresh tip` job step everywhere
- [ ] Remove detached mode steps since we no longer run the workflow as part of the release event

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [ ] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [ ] I have performed a self-review of this change
* [ ] Changes have been tested
* [ ] Changes are documented
* [ ] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by heitorlessa** [comment]
Found a problem we can discuss tomorrow in more detail on best way to approach it.

1. [We update Layer ARNs as soon as Prod Layers are deployed](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/workflows/reusable_deploy_v2_layer_stack.yml#L153) - that is: `docs/index.md`, `examples/**`
2. [We build a new versioned documentation](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/workflows/publish_v2_layer.yml#L144) with these files that are already available in the trunk (`develop`), since new customers should see the latest ARN
3. Versioned docs are built from the latest tip available in `develop` so we can't build a versioned doc with staged changes, at least not by depending on `reusable_publish_docs.yml` workflow

This will fail in the new secure model, because you won't be able to push directly - `docs/index.md` and `examples` - so the versioned docs will be built using the previous Layer ARN.

Don't have a good idea for that yet, so leaving it here for discussion.

---

**Known constraints**

* We can't call a reusable workflow from a step, it must be a dedicated job
* Our reusable docs publishing workflow will always pick up from the latest tip in trunk

**Avenues that are possible as of now**

* We can push to github-pages branch just like before
* We now create a PR with `docs/index.md` and `examples` separately either way
* We could extend our docs publishing workflow to conditionally checkout from a branch instead
    * We create a temp branch with the changes and a PR already

**Comment by heitorlessa** [comment]
> Found a problem we can discuss tomorrow in more detail on best way to approach it.
> 
>     1. [We update Layer ARNs as soon as Prod Layers are deployed](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/workflows/reusable_deploy_v2_layer_stack.yml?rgh-link-date=2023-05-08T14%3A24%3A29Z#L153) - that is: `docs/index.md`, `examples/**`
> 
>     2. [We build a new versioned documentation](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/workflows/publish_v2_layer.yml?rgh-link-date=2023-05-08T14%3A24%3A29Z#L144) with these files that are already available in the trunk (`develop`), since new customers should see the latest ARN
> 
>     3. Versioned docs are built from the latest tip available in `develop` so we can't build a versioned doc with staged changes, at least not by depending on `reusable_publish_docs.yml` workflow
> 
> 
> This will fail in the new secure model, because you won't be able to push directly - `docs/index.md` and `examples` - so the versioned docs will be built using the previous Layer ARN.
> 
> Don't have a good idea for that yet, so leaving it here for discussion.
> 
> **Known constraints**
> 
>     * We can't call a reusable workflow from a step, it must be a dedicated job
> 
>     * Our reusable docs publishing workflow will always pick up from the latest tip in trunk
> 
> 
> **Avenues that are possible as of now**
> 
>     * We can push to github-pages branch just like before
> 
>     * We now create a PR with `docs/index.md` and `examples` separately either way
> 
>     * We could extend our docs publishing workflow to conditionally checkout from a branch instead
>       
>       * We create a temp branch with the changes and a PR already

problem solved!!

I extended the workflow that publish documentation to optionally pull from a different branch or commit ID. Then, I separated creating a PR for docs, and then updating the docs like we used to but now using the temporary branch that hasn't yet being merged.

This PR is quite critical and might be easy to overlook a few areas, so I'll break this PR down now that I've got a working solution.

I'll create separate PRs for:

* [x] Bringing in the new composite action to create PRs - updating Changelog to act as a first example
* [x] Bump the project's version in the trunk via PR
* [x] Repurpose this PR to focus on creating a PR for latest Layer ARNs
* [ ] Document workflows for a big picture

**Comment by heitorlessa** [comment]
First PR created: #2238

**Comment by heitorlessa** [comment]
## This PR is no longer necessary, closing shortly

Broken down into multiple PRs to ease reviewing (in order):

1. https://github.com/awslabs/aws-lambda-powertools-python/pull/2238
2. https://github.com/awslabs/aws-lambda-powertools-python/pull/2239
3. https://github.com/awslabs/aws-lambda-powertools-python/pull/2240

**Comment by ghost** [comment]
Interessante...

**Comment by leandrodamascena** [comment]
> ## This PR is no longer necessary, closing shortly
> Broken down into multiple PRs to ease reviewing (in order):
> 
> 1. [chore(ci): bump package version after release via pull request #2239](https://github.com/awslabs/aws-lambda-powertools-python/pull/2239)
> 2. [chore(ci): bump package version after release via pull request #2239](https://github.com/awslabs/aws-lambda-powertools-python/pull/2239)
> 3. [chore(ci): update layer ARN docs and create PR during release #2240](https://github.com/awslabs/aws-lambda-powertools-python/pull/2240)

@heitorlessa 1 and 2 are the same, is this right?

**Pull request closed without merging**
