### PR TITLE
refactor(logger): improve typing

### LINKED ISSUE #3171: Typing: Getting type errors on logger usage
### Expected Behaviour

We should be able to use `logger.info("log message: %s", "text")` without type errors.

### Current Behaviour

Currently, when logging with the powertools logger, I get the following type error in pylance/pyright:

```
Type of "info" is partially unknown
  Type of "info" is "(msg: object, *args: Unknown, exc_info: Unknown | None = None, stack_info: bool = False, stacklevel: int = 2, extra: Mapping[str, object] | None = None, **kwargs: Unknown) -> None"Pylance[reportUnknownMemberType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnknownMemberType)
```

### Code snippet

```python
from aws_lambda_powertools.logging import Logger

logger = Logger()
logger.info("logging logs %s", "text")
```

### Possible Solution

_No response_

### Steps to Reproduce

Any of the logging level functions issues the same error.

### Powertools for AWS Lambda (Python) version

latest

### AWS Lambda function runtime

3.11

### Packaging format used

PyPi

### Debugging logs

_No response_

### PR DESCRIPTION
**Pull request by aminalaee**
**Issue Number:** #3171

## Summary

Improve typing of `Logger` methods: `info`, 'debug', 'warning', 'critical', ...

The type hints are added per typeshed to avoid any conflicts.

### Changes

> Please provide a summary of what's being changed

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [ ] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [ ] Changes have been tested
* [ ] Changes are documented
* [ ] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by leandrodamascena** [comment]
Hello @aminalaee! Thanks for submitting this PR to fix the type annotation issue. For me it's fine and working as expected,  but I would like the other maintainers to take a look before merging this.
We hope to merge this early next week and include it in our next release, scheduled for March 8th.

**Review by rubenfonseca — APPROVED** [review]

**Comment by rubenfonseca** [comment]
Great job, thank you for adding this!

**Comment by rafrafek** [comment]
Thanks for the PR!

I have found another line causing problems when using Pyright in the strict mode:

```
Type of "append_keys" is "(**additional_keys: Unknown)
```

https://github.com/aws-powertools/powertools-lambda-python/blob/a0141edde7300272ff69554207b659bd40d56a58/aws_lambda_powertools/logging/logger.py#L583

Do you know what type it should be annotated?

**Comment by leandrodamascena** [comment]
> Thanks for the PR!
> 
> I have found another line causing problems when using Pyright in the strict mode:

Hey @rafrafek! Thanks for your comment. It's often challenging to find comments in closed PRs and issues. For better visibility next time, consider opening a new issue or starting a discussion.

> 
> ```
> Type of "append_keys" is "(**additional_keys: Unknown)
> ```
> 
> https://github.com/aws-powertools/powertools-lambda-python/blob/a0141edde7300272ff69554207b659bd40d56a58/aws_lambda_powertools/logging/logger.py#L583
> 
> Do you know what type it should be annotated?

If we annotate it as `object`, Pyright stops complaining.

```python
def append_keys(self, **additional_keys: object) -> None:
    self.registered_formatter.append_keys(**additional_keys)
```

Do you want to send a PR to fix this? Thanks

**Comment by rafrafek** [comment]
Hey @leandrodamascena,

I have created https://github.com/aws-powertools/powertools-lambda-python/pull/3988 with your suggested changes. Thanks!

**Pull request merged**
