### PR TITLE
docs(homepage): Change installation to CDK v2

### LINKED ISSUE #4353: Docs: Change installation from CDK v1 to CDK v2
### What were you searching in the docs?

The installation steps for Powertools using CDK. 

### Is this related to an existing documentation section?

https://docs.powertools.aws.dev/lambda/python/latest/#cdk

### How can we improve?

Changing the example to support CDK v2 instead. The current steps here will fail on CDK v2.

### Got a suggestion in mind?

Change import statements and initializers to CDK v2 formats. :)

https://github.com/aws-powertools/powertools-lambda-python/pull/4351

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

### PR DESCRIPTION
**Pull request by keithrozario**
**Issue number:** #4353 

## Summary

Updated the docs/homepage to reflect CDK v2 instead of CDK v1.

### Changes

Changed the docs/homepage. Installation steps are now for CDK v2 instead CDK v1. The original docs had a CDK v1 implementation which would fail if the user used CDK v2 with an `ImportError`. Also tidied up the environment to use `Aws.Region`. This drops in `Ref: AWS::Region` in the cloudformation stack and should work across all regions.

### User experience

No user experience changes.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>
No. 
**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

image

### CODE REVIEW

**Comment by heitorlessa** [comment]
Hey Keith thanks a lot for this quality improvement 👌 -- could you also open up a docs issue as we require for PRs?

**Comment by keithrozario** [comment]
Thanks @heitorlessa. Done.

https://github.com/aws-powertools/powertools-lambda-python/issues/4353

**Review by leandrodamascena — CHANGES_REQUESTED** [review]
Hello @keithrozario, thank you for bringing this to our attention.
We have linter, type checking and others to try to keep our documentation as real as possible, the reason we don't get this error is because the code is inline in the md file. I'm thinking about moving this file to the `examples` folder and including it in md, so that our CI can observe it. Could you do this please? If you don't have time now, I can do and approve/merge this PR today.

**Comment by keithrozario** [comment]
Thanks @leandrodamascena I can certainly do that -- but perhaps not today :).

But I'm also thinking there's a trade-off. 

For example, this snippet doesn't include the `code`, or `handler` props because it focuses on the most important piece, the `layers` prop of the function. Including details to make this 'workable' might distract from what we're actually trying to communicate in the docs. 

Thoughts?

**Comment by leandrodamascena** [comment]
> For example, this snippet doesn't include the `code`, or `handler` props because it focuses on the most important piece, the `layers` prop of the function. Including details to make this 'workable' might distract from what we're actually trying to communicate in the docs.

Yes, really good points to worry about. But I think we have a solution:

1 – We can highlight lines to show what is most important in that example
2 - We can add a tip button to help the customer understand what that line means

image

Wjhat do you think about?

**Comment by keithrozario** [comment]
Makes sense. I'll work on that soon :)

**Comment by keithrozario** [comment]
I was performing the change today, I thought it would be best to move **all** code snippets to the examples folder. I thought this would make it more consistent, and we would be able to lint/check these files more accurately in the future.

I also noticed the SAR example was using CDK v1, and upgraded that to CDK v2 as well. 

It does introduce a bunch of new example files -- but the index.md now looks a lots more cleaner and consistent just referencing those code blocks rather than including them in-line (in my view at least :))

**Comment by leandrodamascena** [comment]
Hey @keithrozario! Fantastic changes, and we're now able to identify inconsistencies more effectively since we're running linter/formatter on those files. I made some minor adjustments, and it's now ready for merging 🚀

**Review by heitorlessa — APPROVED** [review]

**Review by leandrodamascena — APPROVED** [review]

**Pull request merged**
