### PR TITLE
feat(logger): add dynamic logging key support

### LINKED ISSUE #1167: Logger to support arbitrary key=value style arguments in log statements
> Original author: @CeeBeeCee 

**Runtime:** Python

**Is your feature request related to a problem? Please describe**

As per [discussion](https://github.com/awslabs/aws-lambda-powertools-python/discussions/399) originally posted on Python repo, this feature request is related to Logger being able to use key value arguments in log statements e.g. `logger.info("my message", my_key="value", request_id="123d023f0-alk322f")`.

**Describe the solution you'd like**

I'd like to add additional keys on a per log statement basis by passing an arbitrary number of key=value arguments to `.info, .warn, etc.`.

**Describe alternatives you've considered**

1. Use `extra={}` parameter as supported by Logger and in standard logging library
2. Continue to use [structlog](https://github.com/hynek/structlog)

**If you provide guidance, is this something you'd like to contribute?**

**Additional context**

### PR DESCRIPTION
**Pull request by OGoodness**
**Issue number:**  #1167 

## Summary
Allows extra keywords provided to `logger.xxx` to be added to log via `append_keys`

### Changes

Logger subclass extends the `_log` method, allowing extra keys to be passed in without throwing error due to excess parameters. Routes expected parameters directly to super `_log` after appending excess keys.

### User experience

Nothing is removed from the user, and they can now add logging keys with little effort.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [ X ] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [ X ] I have performed a self-review of this change
* [ X ] Changes have been tested
* [ X ] Changes are documented
* [ ] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>
No
</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by leandrodamascena** [comment]
Hi @OGoodness! Thanks for sending this PR and helping to improve the project!

We suggest not removing the `Issue number:` from the beginning. We use this to run some automation in the PR to keep governance on track. I fixed the labels for now, so it's not a problem anymore. :smile:   

Before I starting to review this PR, could you please check the [errors](https://github.com/awslabs/aws-lambda-powertools-python/runs/8252705866?check_suite_focus=true) in the build action and fix them ? You can run `make pr` locally and check if everything is working. If you have trouble fixing it locally, ping me on [Discord](https://discord.com/invite/B8zZKbbyET) and we can do it together.

Thank you :rocket:

**Comment by OGoodness** [comment]
@leandrodamascena 
Yeah, I ran make pr originally and everything worked fine on my machine. Looks like it had to do with a parameter that got added in python 3.8 and doesn't exist in python 3.7. 

Decided to remove the optional parameter from the input and not pass it in to `_log`, as it's situational at best, and I believe the Logger already accounts for its feature.  

Tested this build using 3.7, so it should be functional

**Comment by OGoodness** [comment]
🤦 
Okay, let's try all 3 then. Hopefully this isn't an environment level thing. 
(Trying out gitpod for the first time, so don't know how that might play into things)

**Comment by OGoodness** [comment]
Ran mypy individually on 3.7, 3.8, 3.9, then ran `make pr`.  (Originally thought `make pr` was only for first runs)
This should be good to go @leandrodamascena Sorry for the wait

Notes:
- Added python version check in the _log, this is to account for the difference mentioned earlier.
- Removed `# type: ignore` from the super calls. Due to the version check, mypy would always flag one or the other as being an unnecessary ignore
- changed `exc_info` to be `Any`, as this removes the need for the expected type that is a union of 3+ other types, simpler to set it to any, as that will avoid complexity if the type is ever changed.

**Comment by leandrodamascena** [comment]
Hello @OGoodness! Sorry for the delay in responding, but we were working on some items for v2 and are now I'm ready to work on it.

I see you've fixed most of the bugs in mypy, but I'm still worried about this support in Python 3.7. Could you please write some tests to cover this new code and make sure everything is working as expected? 
After that we can work (I can help you) on updating the documentation and merge this PR!

Thank you :rocket:

**Comment by heitorlessa** [comment]
As discussed, closing in favour of #1658

**Pull request closed without merging**
