### PR TITLE
feat(logger): support use_datetime_directive for timestamps

### PR DESCRIPTION
**Pull request by huonw**
**Issue #, if available:** #905

## Description of changes:

This adds a new argument `datetime_fmt` that provides more power over the current `datefmt`, by formatting using the `datetime` module rather than the `time` one. This is a separate argument to avoid changing behaviour for any existing users of `datefmt`.

**Checklist**

 

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] Update tests
* [x] Update docs
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by heitorlessa** [comment]
thanks a lot @huonw - I need to finish two other PRs and then I'll get back to this. I think an extra string parameter could confuse customers... perhaps a flag parameter like `use_datetime_format=True` might be more explicit while `datefmt` remains true to its purpose

**Comment by huonw** [comment]
Sounds good!

**Comment by heitorlessa** [comment]
Docs PR finished. Will finish the new feature flags extension tomorrow (non-boolean values) then I get to this in the morning, and we release it ;-) o//!

If you have some good samples that we could add in the docs of some common date formats (e.g. ISO8601), that would be awesome!

**Comment by heitorlessa** [comment]
All other PRs finished, looking into this now, taking the liberty to make some minor changes, docs, all in the same PR so we can merge and release it today o//!!!

**Review by heitorlessa — APPROVED** [review]

**Comment by huonw** [comment]
Thanks for finishing this off (I was on leave). Your changes look great 👍

**Pull request merged**
