### PR TITLE
feat(event_handler): add support for additional response models in OpenAPI schema

### LINKED ISSUE #3542: Feature Request: ability to define additional response models in OpenAPI
### Discussed in https://github.com/aws-powertools/powertools-lambda-python/discussions/3540

<div type='discussions-op-text'>

<sup>Originally posted by **MCR2019** December 19, 2023</sup>
Really excited about the quite new powertools openAPI spec generation so thank to all those who've worked on it and those working on it now :) 

I'm trying to get it working for an endpoint and following the documentation on how to specify responses here:
[Customizing API Operations docs](https://docs.powertools.aws.dev/lambda/python/latest/core/event_handler/api_gateway/#customizing-api-operations)

Specifically I'd like to add custom reponses which the documentation shows as:

```
@app.get(
    "/todos/<todo_id>",
    summary="Retrieves a todo item",
    description="Loads a todo item identified by the `todo_id`",
    response_description="The todo object",
    responses={
        200: {"description": "Todo item found"},
        404: {
            "description": "Item not found",
        },
    },
    tags=["Todos"],
)
def get_todo_title(todo_id: int) -> str:
    todo = requests.get(f"https://jsonplaceholder.typicode.com/todos/{todo_id}")
    todo.raise_for_status()
```

I'd really like to be able to specify the content/schema of the response, maybe as a Pydantic Model which would then generate the response schema in the openAPI spec. (in the same way that the function response type is used).

At the moment I'm only able to get it to work with a basic string which doesn't represent the actual return type/structure.

Is there any more info on what the intention is for how this should be used with a fuller example?

I'm aware that this functionality is quite new so I'm not sure if this is something already on the to do list?

Any info would be great, and thanks again!

</div>

### PR DESCRIPTION
**Pull request by rubenfonseca**
**Issue number:** #3542

### Changes

> Please provide a summary of what's being changed

This PR adds support for additional response models on the OpenAPI specification.

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

- [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
- [x] I have performed a self-review of this change
- [x] Changes have been tested
- [ ] Changes are documented
- [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

- [ ] Migration process documented
- [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by rubenfonseca** [comment]
Note: still need to update documentation before it's ready for review

**Comment by ran-isenberg** [comment]
@rubenfonseca  I dunno if it helps or not but i was able to add custom responses with pydantic models. See this example:
https://github.com/ran-isenberg/aws-lambda-handler-cookbook/pull/784/files#diff-03a550a2c5158da1b1459e42e5799bdfe3809d2563dfb16014d3ea3bcd7cd043R20

```python
501: {
            'description': 'Internal server error',
            'content': {'application/json': {'schema': InternalServerErrorOutput.model_json_schema()}},
        },
```

**Comment by leandrodamascena** [comment]
> @rubenfonseca I dunno if it helps or not but i was able to add custom responses with pydantic models. See this example: [ran-isenberg/aws-lambda-handler-cookbook#784 (files)](https://github.com/ran-isenberg/aws-lambda-handler-cookbook/pull/784/files#diff-03a550a2c5158da1b1459e42e5799bdfe3809d2563dfb16014d3ea3bcd7cd043R20)
> 
> ```python
> 501: {
>             'description': 'Internal server error',
>             'content': {'application/json': {'schema': InternalServerErrorOutput.model_json_schema()}},
>         },
> ```

Hi @ran-isenberg! You can currently use a Pydantic model by dumping it as JSON. But we don't want to force customers to serialize their models manually and need to add more code and stuff, we want to provide a seamless experience serializing/deserializing Pydantic models, Dataclass, scalar types, Python classes, and others. So, after merging this PR you can just pass your Model and we serialize it like this:

```python
@app.get(
        "/",
        responses={
            200: {"description": "200 Response", "content": {"application/json": {"model": User}}},
            202: {"description": "202 Response", "content": {"application/json": {"model": Order}}},
        },
    )
def handler() -> Response[Union[User, Order]]:
    if randbelow(2) > 0:
        return Response(status_code=200, body=User())
    else:
        return Response(status_code=202, body=Order())
```

Thanks

**Comment by ran-isenberg** [comment]
> > @rubenfonseca I dunno if it helps or not but i was able to add custom responses with pydantic models. See this example: [ran-isenberg/aws-lambda-handler-cookbook#784 (files)](https://github.com/ran-isenberg/aws-lambda-handler-cookbook/pull/784/files#diff-03a550a2c5158da1b1459e42e5799bdfe3809d2563dfb16014d3ea3bcd7cd043R20)
> > ```python
> > 501: {
> >             'description': 'Internal server error',
> >             'content': {'application/json': {'schema': InternalServerErrorOutput.model_json_schema()}},
> >         },
> > ```
> 
> Hi @ran-isenberg! You can currently use a Pydantic model by dumping it as JSON. But we don't want to force customers to serialize their models manually and need to add more code and stuff, we want to provide a seamless experience serializing/deserializing Pydantic models, Dataclass, scalar types, Python classes, and others. So, after merging this PR you can just pass your Model and we serialize it like this:
> 
> ```python
> @app.get(
>         "/",
>         responses={
>             200: {"description": "200 Response", "content": {"application/json": {"model": User}}},
>             202: {"description": "202 Response", "content": {"application/json": {"model": Order}}},
>         },
>     )
> def handler() -> Response[Union[User, Order]]:
>     if randbelow(2) > 0:
>         return Response(status_code=200, body=User())
>     else:
>         return Response(status_code=202, body=Order())
> ```
> 
> Thanks

Cool , it's a cleaner experience. 
Did you try it with a more complicated Pydantic model? I tried it and it failed. 
I modeled the 422 response model and pydantic builds you two schemas, where one refrences the other but it cant find the other one, so it throws an error and shows it as empty dict.
can you try this use case @leandrodamascena ?
```python
class Error(BaseModel):
  x: str


class HttpErrors(BaseModel):
  details: List[Error]
```
so  HttpErrors schema will point a $ref to Error schema which does not exist

**Comment by leandrodamascena** [comment]
Looking at this now.

**Comment by leandrodamascena** [comment]
> Cool , it's a cleaner experience. Did you try it with a more complicated Pydantic model? I tried it and it failed. I modeled the 422 response model and pydantic builds you two schemas, where one refrences the other but it cant find the other one, so it throws an error and shows it as empty dict. can you try this use case @leandrodamascena ?
> 
> ```python
> class Error(BaseModel):
>   x: str
> 
> 
> class HttpErrors(BaseModel):
>   details: List[Error]
> ```
> 
> so HttpErrors schema will point a $ref to Error schema which does not exist

Hi @ran-isenberg! I don't see this issue in this PR. It may happen in your local code, but when we merge this PR you will no longer need to "hack" to have Pydantic models in your responses.

```python
from typing import List

import requests
from pydantic import BaseModel, Field

from aws_lambda_powertools.event_handler import APIGatewayRestResolver
from aws_lambda_powertools.utilities.typing import LambdaContext

app = APIGatewayRestResolver(enable_validation=True)
app.enable_swagger(path="/swagger")


class Error(BaseModel):
  x: str


class HttpErrors(BaseModel):
  details: List[Error]

class Todo(BaseModel):
    userId: int
    id_: int = Field(alias="id")
    title: str
    completed: bool


@app.get("/hello", responses={
            200: {"description": "200 Response"},
            500: {"description": "500 Response", "content": {"application/json": {"model": HttpErrors}}},
        })
def get_todos_by_email(email: str) -> List[Todo]:
    todos = requests.get(f"https://jsonplaceholder.typicode.com/todos?email={email}")
    todos.raise_for_status()

    return todos.json()


def lambda_handler(event: dict, context: LambdaContext) -> dict:
    print(app.get_openapi_json_schema())
    return app.resolve(event, context)
```

### SWAGGER
image

**Review by leandrodamascena — CHANGES_REQUESTED** [review]
Hello @rubenfonseca! Amazing work once again :smile:

Please, can you update the documentation and add a new example?
image

**Comment by ran-isenberg** [comment]
> > Cool , it's a cleaner experience. Did you try it with a more complicated Pydantic model? I tried it and it failed. I modeled the 422 response model and pydantic builds you two schemas, where one refrences the other but it cant find the other one, so it throws an error and shows it as empty dict. can you try this use case @leandrodamascena ?
> > ```python
> > class Error(BaseModel):
> >   x: str
> > 
> > 
> > class HttpErrors(BaseModel):
> >   details: List[Error]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so HttpErrors schema will point a $ref to Error schema which does not exist
> 
> Hi @ran-isenberg! I don't see this issue in this PR. It may happen in your local code, but when we merge this PR you will no longer need to "hack" to have Pydantic models in your responses.
> 
> ```python
> from typing import List
> 
> import requests
> from pydantic import BaseModel, Field
> 
> from aws_lambda_powertools.event_handler import APIGatewayRestResolver
> from aws_lambda_powertools.utilities.typing import LambdaContext
> 
> app = APIGatewayRestResolver(enable_validation=True)
> app.enable_swagger(path="/swagger")
> 
> 
> class Error(BaseModel):
>   x: str
> 
> 
> class HttpErrors(BaseModel):
>   details: List[Error]
> 
> class Todo(BaseModel):
>     userId: int
>     id_: int = Field(alias="id")
>     title: str
>     completed: bool
> 
> 
> @app.get("/hello", responses={
>             200: {"description": "200 Response"},
>             500: {"description": "500 Response", "content": {"application/json": {"model": HttpErrors}}},
>         })
> def get_todos_by_email(email: str) -> List[Todo]:
>     todos = requests.get(f"https://jsonplaceholder.typicode.com/todos?email={email}")
>     todos.raise_for_status()
> 
>     return todos.json()
> 
> 
> def lambda_handler(event: dict, context: LambdaContext) -> dict:
>     print(app.get_openapi_json_schema())
>     return app.resolve(event, context)
> ```
> 
> ### SWAGGER
> image

nice! looking forward to adding this to the cookbook and blog post very soon!

**Review by leandrodamascena — APPROVED** [review]
Amazing work @rubenfonseca!

**Pull request merged**
