### PR TITLE
fix(lint): Move `tests/THIRD-PARTY-LICENSES` to root

### PR DESCRIPTION
**Pull request by michaelbrewer**
**Issue #, if available:**

## Description of changes:

Move `tests/THIRD-PARTY-LICENSES` to the correct location 

Side effect was that it was breaking the linting :) 

```
⋊> ~/p/p/aws-lambda-powertools-python on fix-flake8 ⨯ make lint                                                                                                              poetry run isort -rc aws_lambda_powertools tests
poetry run black aws_lambda_powertools tests
All done! ✨ 🍰 ✨
139 files left unchanged.
poetry run flake8 aws_lambda_powertools/* tests/*
tests/THIRD-PARTY-LICENSES:1:1: E902 IndentationError: unindent does not match any outer indentation level
tests/THIRD-PARTY-LICENSES:1:22: E231 missing whitespace after ':'
tests/THIRD-PARTY-LICENSES:1:23: E226 missing whitespace around arithmetic operator
tests/THIRD-PARTY-LICENSES:1:35: E226 missing whitespace around arithmetic operator
tests/THIRD-PARTY-LICENSES:1:46: E226 missing whitespace around arithmetic operator
tests/THIRD-PARTY-LICENSES:3:34: E111 indentation is not a multiple of four
tests/THIRD-PARTY-LICENSES:3:34: E113 unexpected indentation
make: *** [lint] Error 1
```

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] Update tests
* [X] Update docs
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by michaelbrewer** [comment]
@heitorlessa i think this will fix it.

**Comment by heitorlessa** [comment]
If it's not too much to ask, could you update the PR by simply moving this Third party license file to the root of the project? 

I accidentally created in the wrong place and quickly before I left home. There's no need to exclude it from tests

**Comment by michaelbrewer** [comment]
> If it's not too much to ask, could you update the PR by simply moving this Third party license file to the root of the project?
> 
> I accidentally created in the wrong place and quickly before I left home. There's no need to exclude it from tests

sure. I see what you mean :)

**Comment by michaelbrewer** [comment]
@heitorlessa  done

**Comment by heitorlessa** [comment]
Thank you!! Lesson learned to not make any changes in a rush or use the phone to review stuff

**Pull request merged**
