### PR TITLE
chore(ci): splits layer building into a stack per supported architecture

### PR DESCRIPTION
**Pull request by ivica-k**
**Issue number:** #1640 

## Summary
splits layer building into a stack per supported architecture, one for `x86_64` and one for `arm64`. this should bring a speed increase in building and publishing layers because they can be separated and parallelized

### Changes

> Please provide a summary of what's being changed

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [ ] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by ivica-k** [comment]
A work-in-progress PR. I'd appreciate any guidance on the approach, possible edge cases etc. I tried updating the Github part but i'm not sure how to make the layer building steps run in parallel.

**Comment by ivica-k** [comment]
this won't work in situations where `HasARM64Support` is false, the stack won't exist. running the CI job conditionally based on `HasARM64Support` could be an alley to explore.

**Comment by heitorlessa** [comment]
As we discussed on Discord, we'd have to rely on @rubenfonseca to review (whom will be back mid next week).

**Comment by rubenfonseca** [comment]
Looking at this now

**Comment by rubenfonseca** [comment]
Hi @ivica-k thank you for your time looking into this! I've messaged you on your Discord so we can chat about this, would you mind taking a look please? :)

**Comment by rubenfonseca** [comment]
As we discussed on Discord, when we originally created [the issue](https://github.com/aws-powertools/powertools-lambda-python/issues/1640), what was taking a lot of time was building the actual layer, since ARM64 needs to [be emulated on top of X86](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/workflows/publish_v2_layer.yml#L119-L131). In the meantime, through the use of custom workers, we reduced the time down to 5 minutes, which we believe it's pretty reasonable. 

Screenshot 2023-08-15 at 11 34 10

We really appreciate your effort on this one, but we will close the PR and the original issue. This was our fault -- we should have closed the issue in the first place [when the performance was acceptable](https://xkcd.com/1205/). Please accept our sincere apologies!

**Pull request closed without merging**
