### PR TITLE
docs: add info how to get layer versions from the SAR for the layers 

### PR DESCRIPTION
**Pull request by am29d**
**Issue #, if available:**

## Description of changes:

The AWS console does not show the available versions of the SAR app for the layers we have recently published. I added the CLI command this the ARN to fetch the available versions.

**Checklist**

 

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [ ] Update tests
* [x] Update docs
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by heitorlessa** [comment]
Great addition. While you're at it, could you add some quick notes on what to do after deployed?

Where can they find the Layer Arn to use? Outputs?

**Review by heitorlessa — CHANGES_REQUESTED** [review]
Add instruction on how to find the Layern ARN after deploying the SAR App

**Comment by am29d** [comment]
Unfortunately, you have first to deploy the SAR app to get the `LayerVersionArn` as an exported value that can be referenced in a Lambda function resource definition. You can not do this within one SAM template and deploy the app and the lambda in one go :(. 

I added two options in the documentation, either way you need to deploy two times.

**Comment by am29d** [comment]
close this pr and reopened in #145 , because I screw up my fork repo and had to create new.

**Pull request closed without merging**
