### PR TITLE
fix(deps): update build system to poetry-core

### LINKED ISSUE #1646: Bug: Build fails if `poetry-core>=1.1.0a6` is not specified
### Expected Behaviour

Build succeeds

### Current Behaviour

Build fails.

Logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=594749&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

### Code snippet

```python
python -m pip install . -vv
```

### Possible Solution

As described in https://github.com/python-poetry/poetry/issues/4983 it can be fixed by adding `poetry-core>=1.1.0a6` to the build requirements. 

Additionally, it might make sense to switch to `poetry-core`: https://github.com/python-poetry/poetry-core

### Steps to Reproduce

Build package
PR: https://github.com/conda-forge/aws-lambda-powertools-feedstock/pull/53

### AWS Lambda Powertools for Python version

latest

### Packaging format used

PyPi

### Debugging logs

```python
Processing $SRC_DIR
  Added file://$SRC_DIR to build tracker '/tmp/pip-build-tracker-vc54bee8'
  Created temporary directory: /tmp/pip-modern-metadata-o32viuml
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/home/conda/feedstock_root/build_artifacts/aws-lambda-powertools_1666621594121/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
      main()
    File "/home/conda/feedstock_root/build_artifacts/aws-lambda-powertools_1666621594121/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/conda/feedstock_root/build_artifacts/aws-lambda-powertools_1666621594121/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/home/conda/feedstock_root/build_artifacts/aws-lambda-powertools_1666621594121/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
      poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
    File "/home/conda/feedstock_root/build_artifacts/aws-lambda-powertools_1666621594121/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.10/site-packages/poetry/core/factory.py", line 43, in create_poetry
      raise RuntimeError("The Poetry configuration is invalid:\n" + message)
  RuntimeError: The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
```

### PR DESCRIPTION
**Pull request by rubenfonseca**
**Issue number:** #1646

### Changes

> Please provide a summary of what's being changed

This bumps the build system to use `poetry-core`.

Please note that I'm way out of my confort zone here, so this PR might not be the right solution for the symptoms.
But locally it fixed the problem for me.

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [ ] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by rubenfonseca** [comment]
No idea why tests are not running here.

**Comment by heitorlessa** [comment]
> No idea why tests are not running here.

it's because it's not changing any `python` file.

**Review by heitorlessa — APPROVED** [review]
LGTM. I've just created a new fresh poetry project and it uses this new build-backend. We can merge, test any code quality workflow too.

**Comment by BastianZim** [comment]
Thanks everyone! My two cents from what I've seen in the wild: The switch only involves that and should work out of the box.

**Pull request merged**
