### PR TITLE
feat(apigateway): access parent api resolver from router

### PR DESCRIPTION
**Pull request by cakepietoast**
**Issue #, if available:** #834

## Description of changes:

Enable access to parent api resolver class from child router classes. Example:

app.py
```python
...
app = ApiGatewayResolver()
app.include_router(users.router, prefix="/users") # prefix 

def lambda_handler(event: Dict, context: LambdaContext):
    return app.resolve(event, context)

```

users.py
```python
...

router = Router()

@router.get("/users/")
def get_users() -> Dict:
    router.api_resolver.custom_functionality()
    return {"message": "success"}

```

**Checklist**

 

* [X] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [X] Update tests
* [X] Update docs
* [X] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by heitorlessa** [comment]
Should we add a note in the docs? E.g. subclassing ApiGatewayResolver etc

**Comment by cakepietoast** [comment]
> Should we add a note in the docs? E.g. subclassing ApiGatewayResolver etc

I think if we add documentation here it needs to be a more widely scoped section explaining how and why you might want to subclass `ApiGatewayResolver` as opposed to just the particular detail this PR implements. I'd like to try and understand how common this is, and what some of the use cases are, before expanding on the docs there.

**Comment by cakepietoast** [comment]
> Should we add a note in the docs? E.g. subclassing ApiGatewayResolver etc

I think if we add documentation here it needs to be a more widely scoped section explaining how and why you might want to subclass `ApiGatewayResolver`, as opposed to just the particular detail this PR implements. I'd like to try and understand how common this is, and what some of the use cases are, before expanding on the docs there.

**Comment by heitorlessa** [comment]
Agree - that’s what I meant by whether it should be in the docs (explained
with an example).

LGTM

**Review by heitorlessa — APPROVED** [review]

**Pull request merged**
