### PR TITLE
feat(data-classes): adds support for S3 event notifications through EventBridge

### LINKED ISSUE #1656: Feature request: Support S3 Event Notifications Model for Event Bridge
### Use case

With the introduction of S3 Event Notifications in Event Bridge [here](https://aws.amazon.com/blogs/aws/new-use-amazon-s3-event-notifications-with-amazon-eventbridge/) we need the ability to quickly unpack the event payload from the Event Bridge Envelope.

The structure of the message is described [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ev-events.html).

### Solution/User Experience

It would suffice to extend the s3 models in the the parser [module](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/aws_lambda_powertools/utilities/parser/models/s3.py).

### Alternative solutions

Have the module instantiated at the project level and just use the envelope unpacking mechanism.

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-python/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Java](https://github.com/awslabs/aws-lambda-powertools-java/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

### PR DESCRIPTION
**Pull request by ivica-k**
#1656 

### Changes

adds dataclasses/events support for S3 event notifications through EventBridge

Note: Relies on PR #1982 being merged since they share events. I'll happily rebase once #1982 is merged.

Note2: Pay special attention to me overriding `mypy` checks with `# type: ignore[override]`

### User experience

```python
    from aws_lambda_powertools.utilities.data_classes import event_source, S3EventBridgeNotificationEvent

    @event_source(data_class=S3EventBridgeNotificationEvent)
    def lambda_handler(event: S3EventBridgeNotificationEvent, context):
        bucket_name = event.detail.bucket.name
        file_key = event.detail.object.key
```

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by ivica-k** [comment]
I can't reproduce the code quality failing on Python 3.7 locally. Added `# noqa: A003` to try and silence and locally it passes with `make pr`.

**Review by heitorlessa — CHANGES_REQUESTED** [review]
looks great - you're accidentally including `parser` commits ;) Please ping after removing it and I'll pull to test it, push any necessary changes, and merge it

**Comment by heitorlessa** [comment]
> I can't reproduce the code quality failing on Python 3.7 locally. Added `# noqa: A003` to try and silence and locally it passes with `make pr`.

Looking

**Comment by heitorlessa** [comment]
hmmm that's odd. I thought it was dependency lock being out of sync locally vs CI, but even after rebasing it's causing that problem in CI only -- it's almost as if `git checkout` is dirty. I'll do some more digging

**Comment by ivica-k** [comment]
> looks great - you're accidentally including `parser` commits ;) Please ping after removing it and I'll pull to test it, push any necessary changes, and merge it

Events JSON files are needed in both PRs (#1982  and this one) so I created this branch from `ivica-k:feat(event-source)-1656-s3-event-eventbridge`. Once the parser utility from #1982 is merged I'll rebase this branch on `develop`.

Unless you have a better idea on how to approach this... :)

**Comment by heitorlessa** [comment]
> > looks great - you're accidentally including `parser` commits ;) Please ping after removing it and I'll pull to test it, push any necessary changes, and merge it
> 
> Events JSON files are needed in both PRs (#1982 and this one) so I created this branch from `ivica-k:feat(event-source)-1656-s3-event-eventbridge`. Once the parser utility from #1982 is merged I'll rebase this branch on `develop`.
> 
> Unless you have a better idea on how to approach this... :)

Oh I was referring to these: https://github.com/awslabs/aws-lambda-powertools-python/pull/1990/files#diff-0640cb056db90940195cc25741ffec24b333d690b27936650a16f163bd74239cR61

If it's easier to merge the parser one first and rebase, let's go for it then; I don't mind. Got two upcoming meetings but should get the parser reviewed and merged today

**Comment by heitorlessa** [comment]
Confirmed it's the GH Action pulling a dirty commit that isn't in this history: `b9d1c6364cb857c3c23f670f15fc64d81a82d488`.

I'll pause this for now, work on the Parser PR, then we do git fixups to get GH Action to behave

image

**Comment by heitorlessa** [comment]
Pulling this now ;)

**Comment by heitorlessa** [comment]
I can't understand for the life of me why GH Actions is still picking up an old commit. Could you create a new one? Never seen this before.

**Comment by ivica-k** [comment]
Closing this for now - will create a fresh PR

**Pull request closed without merging**
