### PR TITLE
feat(parameters): Add force_fetch option

### PR DESCRIPTION
**Pull request by michaelbrewer**
**Issue #, if available:**

https://github.com/awslabs/aws-lambda-powertools-python/issues/131

## Description of changes:

Changes:
- Add new `force_fetch` to always fetch the latest value, even if there is a cached value

Example based on https://github.com/alexcasalboni/ssm-cache-python#complex-invalidation-based-on-signals
```python3
import os
from aws_lambda_powertools.utilities import parameters


class InvalidCredentials(Exception):
    """Raised when client get an invalid credentials error"""


class Client:
    password = None

    def configure(self, password):
        self.password = password

    def read_record(self):
        """Might raise an InvalidCredentials exception """


DB_PASS_PARAM = os.environ["DB_PASS_PARAM"]
db_client = Client()
db_client.configure(parameters.get_parameter(DB_PASS_PARAM))


def refresh_db_password():
    db_client.configure(parameters.get_parameter(DB_PASS_PARAM, force_fetch=True))


def read_record(is_retry=False):
    try:
        return db_client.read_record()
    except InvalidCredentials:
        if not is_retry:  # avoid infinite recursion
            refresh_db_password()  # force parameter refresh
            return read_record(is_retry=True)


def handler(event, context):
    return {"record": read_record()}
```

**Checklist**

 

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by michaelbrewer** [comment]
@heitorlessa I added a `force_update` option but i did notice that the `sdk_options` is confusing things for PyCharm

Screen Shot 2021-03-14 at 3 13 10 AM

**Comment by michaelbrewer** [comment]
@heitorlessa I made it an explicit option throughout, the question is what should it be called?

`force_update`, `refresh`, `force_fetch` ?

**Comment by heitorlessa** [comment]
For completion, as @nmoutschen suggested, let's go with `force_fetch` as that doesn't make assumption whether we have something cache to be ignored.

**Comment by michaelbrewer** [comment]
> For completion, as @nmoutschen suggested, let's go with `force_fetch` as that doesn't make assumption whether we have something cache to be ignored.

Ok @nmoutschen  @heitorlessa  i have made the update to `force_fetch`

**Review by heitorlessa — APPROVED** [review]

**Pull request merged**
