### PR TITLE
feat(runtime): add Python 3.13 support

### LINKED ISSUE #5411: Maintenance: Support for Python 3.13
### Why is this needed?

According to the [official AWS documentation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html), the AWS Lambda Python 3.13 runtime will be released in November 2024, and considering that Python 3.13 has had some changes in this release, we need to start working to detect and fix any issues and be ready when this runtime is released.

*This date is indicative only and subject to change.

Image

### Which area does this relate to?

_No response_

### Solution

Use this playbook to add support for Python 3.13.

### 1. Prerequisites

- The new AWS Lambda Python runtime needs to be [supported by CDK](https://github.com/aws/aws-cdk/releases)
- The new AWS Lambda Python runtime needs to be [supported  by SAM](https://github.com/aws/aws-sam-cli/releases)
- The new Python version needs to be [supported  by any required dependencies](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/pyproject.toml#L40)

### 2. Testing locally

- Must install the new Python runtime version and run all the tests and linters locally to see if anything is breaking, by running `make pr`

### 3. Adding the new supported runtime in the layer construct

On the [CDK Layer constructor](https://github.com/aws-powertools/powertools-lambda-python/tree/develop/layer_v3), do:

- Bump the CDK version to support the new AWS Lambda Python runtime version
- Change the supported runtimes to include the new runtime
- Make sure tests still pass by running `poetry run pytest tests`
- Submit and merge a PR with the changes

### 4. Updating workflows and templates

- Update all files inside the `.github` directory to include the new runtime version. This includes the e2e workflow
  - Example: [this example PR](https://github.com/awslabs/aws-lambda-powertools-python/pull/2137) added support to 3.10

### 5. Layer

- Bump the CDK version on the [on the root of the repository](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/package.json), by editing `package.json` and running `npm install`
- Inside the layer directory: bump the [Layer construct version](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/layer_v3/pyproject.toml) by editing the `pyproject.toml` and running `poetry lock`.

### 6. SAR

- Add the new runtime to the `layer_v3/sar/template.txt`

### 7. Change the PyPi metadata

- Edit the `pyproject.toml` and [update the poetry classifiers](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/pyproject.toml#L7) to include the new runtime.

### 8. Open a PR and run E2E tests

- Open a new PR with the changes made in steps 4, 5, 6 and 7.
- Wait for the automated tests to pass (so the tests run against the new runtime)
- Manually schedule [an E2E workflow](https://github.com/aws-powertools/powertools-lambda-python/actions/workflows/run-e2e-tests.yml) on that branch (so the automated tests run against the new runtime)
    - Example: [this example PR](https://github.com/aws-powertools/powertools-lambda-python/pull/2137) added support to 3.10

### 9. Examples

- Update the SAM/Terraform examples to use the latest version of the supported runtime.

### 10. Merge and release

- If everything is green you should be able to merge the PR and release a new version, which will generate and publish the new Layer and SAR template.
- Celebrate and start using this new runtime! 🍺 🎉

### Acknowledgment

- [x] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [x] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### LINKED ISSUE #5547: Maintenance: Bump the CDK version to add Python 3.13 support
### Why is this needed?

Bump the CDK version to add Python 3.13 support

### Which area does this relate to?

Other

### Solution

_No response_

### Acknowledgment

- [x] This request meets [Powertools for AWS Lambda (Python) Tenets](https://docs.powertools.aws.dev/lambda/python/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Java](https://github.com/aws-powertools/powertools-lambda-java/), [TypeScript](https://github.com/aws-powertools/powertools-lambda-typescript/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### PR DESCRIPTION
**Pull request by leandrodamascena**
**Issue number:** #5411

### Changes

Lambda already [published the base image ](https://github.com/aws/aws-lambda-base-images/issues/168#issuecomment-2448024804) for Python 3.13 (preview mode) and then we can start adding support for this new runtime in Powertools.

### User experience

WIP

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [x] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by leandrodamascena** [comment]
Constructor running with Python 3.13 - https://github.com/leandrodamascena/test-powertools-action/actions/runs/11828109022/job/32958160741

**Comment by dreamorosi** [comment]
CI is failing with 

```
OSError: [Errno 28] No space left on device
```

😰

**Comment by leandrodamascena** [comment]
e2e test is green

https://github.com/aws-powertools/powertools-lambda-python/actions/runs/11828379716/job/32959447655

**Comment by leandrodamascena** [comment]
> CI is failing with
> 
> ```
> OSError: [Errno 28] No space left on device
> ```
> 
> 😰

To be honest, this was my fault. I was running the CDK layer tests with an matrix of all Python versions, but I don't need that because I don't want to test if it's being built on a specific Python version, we know that build, I want to know if [given a Python Runtime](https://github.com/aws-powertools/powertools-lambda-python/pull/5527/files#diff-3fc6da457aa2187e3c04cf45bbe49f765cb8f86a458a4204c3a26c22ff8a951cR28) I can build the dockefile and synthesize CloudFormation.

Lets wait the CI run again.

**Comment by dreamorosi** [comment]
Ok thanks- can we also address the SonarCloud findings?

**Comment by leandrodamascena** [comment]
> 3 New issues

I'd rather not change them. These warnings are related to the Dockerfile in the sense that you're deploying a Docker image and it can create extra layers, add unnecessary Docker layer space, and so on. But that's not our case, the only reason we use a `Dockerfile` is to build using the actual Lambda environment (base images) and address things like libraries that need to be installed for a specific architecture or OS, and architecture. We don't use this Dockerfile to serve Docker images to customers, we just "build" and extract the resulting files from that build.

I'll mark all of them as "accepted"

**Review by dreamorosi — APPROVED** [review]
Thanks for the hard work on this @leandrodamascena!

**Comment by leandrodamascena** [comment]
@dreamorosi ready for review.

**Pull request merged**
