### PR TITLE
feat(event-handler): Support AppSyncResolverEvent subclassing

### PR DESCRIPTION
**Pull request by whardier**
…vent

No outsstanding issue

## Description of changes:

Allows for custom subclass of AppSyncResolverEvent data_class to be offered to AppSyncResolver.resolve

**Checklist**

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
* [x] Update tests
* [x] Update docs
* [x] PR title follows [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-python/blob/376ec0a2ac0d2a40e0af5717bef42ff84ca0d1b9/.github/semantic.yml#L2)

## Breaking change checklist

Not breaking

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by whardier** [comment]
Alternatively the annotation 'current_event: AppSyncResolverEvent' could simply be overridden and then utilized via self.__annotations__['current_event'](event) .. but I'm not sure if __annotations__ is optimized out or how recognized that pattern is.

**Comment by heitorlessa** [comment]
Hey @whardier, thanks for the contribution!!

Could you share a sample subclass that you created for AppSync event?

This will help me understand the use case, and what's potentially missing from the AppSyncEvent class before we add tests for this PR.

Thank you

**Comment by whardier** [comment]
Sure.. the following is a non-patched solution to provide the custom properties we are accessing from the underlaying _data:

```python
from aws_lambda_powertools.utilities.data_classes.appsync_resolver_event import (
    AppSyncIdentityCognito,
    AppSyncResolverEvent,
)

class CustomAppSyncResolverEvent(AppSyncResolverEvent):
    @cached_property
    def auth_client_id(self) -> Optional[str]:
        auth_client_id: Optional[str] = None
        if isinstance(self.identity, AppSyncIdentityCognito):
            auth_client_id = self.identity.claims.get("custom:client_id")
        return auth_client_id

    @cached_property
    def auth_user_profile_id(self) -> Optional[str]:
        auth_user_profile_id: Optional[str] = None
        if isinstance(self.identity, AppSyncIdentityCognito):
            auth_user_profile_id = self.identity.claims.get("custom:user_profile_id") or self.identity.sub
        return auth_user_profile_id

# ... below to assist with hints

class CustomAppSyncResolver(AppSyncResolver):
    current_event: CustomAppSyncResolverEvent
    
# ... specific enough sample appsync lambda event handler

@appsync.resolver(type_name="Mutation", field_name="logThingUserEvent")
@validate_arguments
@typechecked
def log_thing_user_event(
    event_type: ThingUserEventTypeEnum,
    measure_reference: Annotated[str, Field(max_length=256)],
    measure_source: Annotated[str, Field(max_length=32)] = DEFAULT_THING_USER_EVENT_APPSYNC_METRIC_SOURCE,
):

    # ... sample code
    
    auth_client_id: Optional[str] = appsync.current_event.auth_client_id
    auth_user_profile_id: Optional[str] = appsync.current_event.auth_user_profile_id
    
    # ... other junk

@core_tracer.capture_lambda_handler
@core_logger.inject_lambda_context(correlation_id_path=correlation_paths.APPSYNC_RESOLVER)
@event_source(data_class=CustomAppSyncResolverEvent)
@typechecked
def appsync_handler(event: CustomAppSyncResolverEvent, context: AnyLambdaContext) -> dict:

    # NOTE: Until aws lambda powertools allows for hooks/class references to be part of the resolve method to set up a
    # proper current_event with a subclassed dataclass and repeat the innards of the resolve method here (SRS).

    appsync.current_event = event
    appsync.lambda_context = context
    resolver = appsync._get_resolver(event.type_name, event.field_name)
    return resolver(**event.arguments)
    
```

The proposed patch mimics a bit of the model_class approach seen elsewhere in this project.  However a sneaky pattern to do this is as follows and seems to be gaining in popularity:

```python
class LibraryDataClass:
    pass


class CustomDataClass(LibraryDataClass):
    @property
    def custom_property(self):
        return "custom property data"


class LibraryExecutionClass:
    data: LibraryDataClass

    def execute(self):
        data_class = self.__annotations__["data"]
        self.data = data_class()


class CustomExecutionClass(LibraryExecutionClass):
    data: CustomDataClass


# >>> custom_executor = CustomExecutionClass()
# >>> custom_executor.execute()
# >>> custom_executor.data.custom_property
# 'custom property data'
```

**Comment by whardier** [comment]
I concerned that using model as a kwarg here would lead to thoughts that this should be a parser.model rather than a dictwrap data_class.  I know I would have been confused seeing model.

**Comment by heitorlessa** [comment]
> I concerned that using model as a kwarg here would lead to thoughts that this should be a parser.model rather than a dictwrap data_class. I know I would have been confused seeing model.

That's a great point. I find naming hard because even `data_class` could lead to discussions like #481.

How does `data_model` sound? I've made all changes necessary - docs, tests, mypy, agreeing on that and we can merge and release ;)

**Comment by nmoutschen** [comment]
> > I concerned that using model as a kwarg here would lead to thoughts that this should be a parser.model rather than a dictwrap data_class. I know I would have been confused seeing model.
> 
> That's a great point. I find naming hard because even `data_class` could lead to discussions like #481.
> 
> How does `data_model` sound? I've made all changes necessary - docs, tests, mypy, agreeing on that and we can merge and release ;)

Sharing my 2 cents here, I'd personally prefer `data_model` as `model` is quite overloaded in different Python frameworks and libraries.

**Comment by heitorlessa** [comment]
Waiting for @whardier before we merge it

**Comment by whardier** [comment]
I'm still down with something as simple as data_class (as seen here: `@event_source(data_class=CustomAppSyncResolverEvent)
`) but I'm not as behind the scenes on this project ;) - I can't find any other examples on where passing the data_class class name is done any other way.  I will have to catch up on #481.  I really dig the dict wrapper and feel it is appropriately named and unfortunately overlapping other useful naming.  For continuity sake I would prefer to see data_class used until a breaking change can be made to ultimately address any concerns surrounding it.

My preferences aside.  I approve this and thank you for catching the __call__ case and handling the typing the proper way.  It was nice being able to submit some thoughts this way and see changes come back as code.

**Comment by heitorlessa** [comment]
We'll keep it as `data_model` as the amount of energy spent on #481 was abnormal on naming things - I'm merging and release it this week ;)

Thanks a lot again @whardier

**Pull request merged**
