### PR TITLE
docs(i-made-this): add new article about best practices for accelerating serverless development 

### PR DESCRIPTION
**Pull request by ran-isenberg**
**Issue number:**#4517

## Summary
added reference to an AWS article
### Changes

> Please provide a summary of what's being changed

### User experience

> Please share what the user experience looks like before and after this change

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [ ] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [ ] I have performed a self-review of this change
* [ ] Changes have been tested
* [ ] Changes are documented
* [ ] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Review by leandrodamascena — APPROVED** [review]
Thanks for sharing this blog post @ran-isenberg!

**Comment by leandrodamascena** [comment]
Pls I need approval here @sthulb @heitorlessa

**Review by heitorlessa — APPROVED** [review]

**Comment by pavitra-infocusp** [comment]
It will be useful to post a link to where we can read this...

**Comment by ran-isenberg** [comment]
> It will be useful to post a link to where we can read this...

it's in the issue that is linked , or in the PR itself..
or just here.. https://aws.amazon.com/blogs/infrastructure-and-automation/best-practices-for-accelerating-development-with-serverless-blueprints

**Pull request merged**
