### PR TITLE
fix: parser S3Model not compatible with ObjectRemoved events

### PR DESCRIPTION
**Pull request by ran-isenberg**
issue https://github.com/awslabs/aws-lambda-powertools-python/issues/1637

### CODE REVIEW

**Comment by ran-isenberg** [comment]
@heitorlessa @barreeeiroo FYI

**Comment by barreeeiroo** [comment]
Thanks @ran-isenberg! I'm back with my laptop, so I was about to test it now. Would it be fine if I cherrypick your commit into a single PR?

**Comment by ran-isenberg** [comment]
Yeah sure np! I had to make some fixes to the validator.

**Comment by barreeeiroo** [comment]
I see you added an `if s3_object`. Is it really needed? I added an additional test case (to make sure we throw the exception), and it seems to be passing without it.
The `root_validator` should run after parsing the object, so technically `s3_object` is never `None` (otherwise a `ValidationException` is thrown earlier.

**Comment by ran-isenberg** [comment]
> I see you added an `if s3_object`. Is it really needed? I added an additional test case (to make sure we throw the exception), and it seems to be passing without it. The `root_validator` should run after parsing the object, so technically `s3_object` is never `None` (otherwise a `ValidationException` is thrown earlier.

no, it's not needed, i think you can remove the extra test case too.
I wrote an earlier version with pre=True but then removed it, forgot to remove this if.

**Comment by barreeeiroo** [comment]
I think it should be done now then. Can you double-check https://github.com/awslabs/aws-lambda-powertools-python/pull/1638 to see if I missed anything from your changes?

**Comment by heitorlessa** [comment]
@leandrodamascena let's merge @ran-isenberg into @barreeeiroo PR, and make sure @ran-isenberg is a co-author in that PR

**Comment by heitorlessa** [comment]
nvm, it is already in (need coffee). I'll merge and add Ran as a co-author

**Comment by ran-isenberg** [comment]
@heitorlessa  it's already merged there

**Pull request closed without merging**
