### PR TITLE
fix(typing): resolved_headers_field is not Optional

### LINKED ISSUE #4147: Static typing: resolved_headers_field is not Optional
### Static type checker used

pyright/pylance

### AWS Lambda function runtime

3.12

### Powertools for AWS Lambda (Python) version

latest

### Static type checker info

```
Expression of type "Dict[str, Any] | None" cannot be assigned to declared type "dict[str, list[str]]"
  Type "Dict[str, Any] | None" cannot be assigned to type "dict[str, list[str]]"
    "None" is incompatible with "dict[str, list[str]]"
```

### Code snippet

```python
import json
from aws_lambda_powertools.event_handler.router import ALBRouter
router = ALBRouter()
@router.get("/")
def get_headers() -> str:
    headers: dict[str, list[str]] = router.current_event.resolved_headers_field
    return json.dumps(headers)
```
```


### Possible Solution

Remove `Optional` 

```diff
- def resolved_headers_field(self) -> Optional[Dict[str, Any]]:
+ def resolved_headers_field(self) -> Dict[str, Any]:
```

### PR DESCRIPTION
**Pull request by tonnico**
**Issue number: #4147**

### Changes

resolved_headers_field is a dict comprehension and can't be None.

### User experience

The user can expect a dict at any time.

## Checklist

If your change doesn't seem to apply, please leave them unchecked.

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda/python/#tenets)
* [x] I have performed a self-review of this change
* [x] Changes have been tested
* [ ] Changes are documented
* [x] PR title follows [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-python/blob/develop/.github/semantic.yml)

<details>
<summary>Is this a breaking change?</summary>

**RFC issue number**:

Checklist:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

</details>

## Acknowledgment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

### CODE REVIEW

**Comment by rubenfonseca** [comment]
Thank you for submitting this! Let's discuss it on the issue first to see what's the best way forward.

**Comment by rubenfonseca** [comment]
We're parking this PR for now until we start working on v3 (very soon)

**Comment by heitorlessa** [comment]
hey @Wurstnase I'm gonna be pushing additional fixes to complete this PR

**Comment by heitorlessa** [comment]
E2E tests pass locally

**Comment by heitorlessa** [comment]
merging. Codecov needs to be revisited; pushed a few false positives but coverage is way below than I expected.

**Pull request merged**
